### ISSUE TITLE
Errors 'EncodeError' frequently appearing in stage/pod worker pod. 

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#1122]
## Summary
stage/prod worker pods is frequently logging error message as "EncodeError(TypeError('Object of type sqs.Message is not JSON serializable'))".  This issue is already being discussed in following slack thread.
https://ansible.slack.com/archives/C8VGAPJNN/p1643268210134100

```
2022-02-10 23:05:37,419 | ERROR | 8 | trace.py:_log_error:265 | requestid:17e658a2-435c-4978-9571-b8d0be86b367 | Task api.clouds.aws.tasks.analyze_log[bda13f17-d377-4021-9dc3-20e9d0be95ba] raised unexpected: EncodeError(TypeError('Object of type sqs.Message is not JSON serializable'))
Traceback (most recent call last):
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type sqs.Message is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 518, in trace_task
    task.backend.mark_as_done(
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/celery/backends/base.py", line 162, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/celery/backends/base.py", line 962, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/celery/backends/base.py", line 418, in encode
    _, _, payload = self._encode(data)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/celery/backends/base.py", line 422, in _encode
    return dumps(data, serializer=self.serializer)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/usr/lib64/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/serialization.py", line 43, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/cloudigrade/.venv/lib/python3.9/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type sqs.Message is not JSON serializable
```

## Steps to Reproduce

There are no explicit steps  to reproduce this issue . These are the only error messages which frequently appearing on stage/prod worker  

## Expected Result

-  deployed Environment should be clean and without any error messages.

## Actual Result

-  'EncodeError' frequently appearing in stage/pod worker pod. 

## Additional context
- These errors are seen  in prod and stage both environment.
-  Following sources creation messages showing error 'CG3002' . Is it side effect of this error?

**Comment by paraggit** [comment]
I have observed the logs since this fix has merged. No 'JSON serializable' errors seen  in the logs. I will move to close this issue.
