### ISSUE TITLE
cloudigrade cannot talk to RabbitMQ when running in OpenShift

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#241]
When running cloudigrade in OpenShift, by default on a dev environment it cannot talk to RabbitMQ  because OpenShift is "helpfully" creating and setting a bunch of environment variables that override our defaults.

### Steps to reproduce
1. `make oc-up-all`
2. `oc rsh -c cloudigrade $(oc get pods -o jsonpath='{.items[*].metadata.name}' -l name=cloudigrade) scl enable rh-postgresql96 rh-python36 -- python manage.py shell -c "from account.tasks import enqueue_ready_volume; enqueue_ready_volume('import-ami-05c88748fa241d139', 'vol-027078f6ae277654f', 'us-east-1')"`

### Expected result

No errors and cloudigrade should quickly handle the call that writes a message to a queue in RabbitMQ.

### Actual result

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/core/management/commands/shell.py", line 86, in handle
    exec(options['command'])
  File "<string>", line 1, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 155, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 95, in enqueue_ready_volume
    add_messages_to_queue('ready_volumes', messages)
  File "/opt/cloudigrade/account/util.py", line 161, in add_messages_to_queue
    with kombu.Connection(settings.RABBITMQ_URL) as conn:
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/connection.py", line 181, in __init__
    url_params = parse_url(hostname)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/url.py", line 34, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/parse.py", line 167, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'tcp:'
command terminated with exit code 1
```

### Additional details

This appears to be happening because OpenShift is autogenerating an environment variable for `RABBITMQ_PORT` that is not an integer that we expect. You can see this by looking at the environment variables running in cloudigrade's pod:

`oc rsh -c cloudigrade $(oc get pods -o jsonpath='{.items[*].metadata.name}' -l name=cloudigrade) env | grep RABBIT`

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cloudigrade-2-fzz9x
TERM=xterm
DJANGO_DATABASE_NAME=postgres
AWS_DEFAULT_REGION=us-east-1
DJANGO_DATABASE_HOST=postgresql.myproject.svc
RABBITMQ_USER=guest
DJANGO_ALLOWED_HOSTS=*
DJANGO_DATABASE_PASSWORD=postgres
DJANGO_SETTINGS_MODULE=config.settings.prod
DJANGO_DATABASE_USER=postgres
DJANGO_DEBUG=False
RABBITMQ_PASSWORD=guest
RABBITMQ_HOST=rabbitmq-persistent.myproject.svc
KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1
POSTGRESQL_PORT_5432_TCP_PORT=5432
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_53_UDP_PORT=53
CLOUDIGRADE_PORT_80_TCP=tcp://172.30.179.148:80
POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
RABBITMQ_SERVICE_HOST=172.30.15.187
RABBITMQ_PORT_15672_TCP=tcp://172.30.15.187:15672
POSTGRESQL_SERVICE_HOST=172.30.35.118
KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53
RABBITMQ_PORT_5672_TCP_ADDR=172.30.15.187
RABBITMQ_PORT_15672_TCP_PROTO=tcp
KUBERNETES_SERVICE_HOST=172.30.0.1
KUBERNETES_SERVICE_PORT_DNS=53
KUBERNETES_PORT_443_TCP_PORT=443
POSTGRESQL_PORT_5432_TCP_PROTO=tcp
RABBITMQ_SERVICE_PORT_RABBITMQ=5672
RABBITMQ_PORT=tcp://172.30.15.187:5672
KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1
CLOUDIGRADE_PORT=tcp://172.30.179.148:80
CLOUDIGRADE_PORT_80_TCP_PORT=80
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://172.30.0.1:443
KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443
POSTGRESQL_SERVICE_PORT=5432
POSTGRESQL_PORT_5432_TCP=tcp://172.30.35.118:5432
RABBITMQ_SERVICE_PORT_RABBITMQ_MANAGEMENT=15672
KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1
KUBERNETES_SERVICE_PORT_DNS_TCP=53
KUBERNETES_PORT_53_TCP_PROTO=tcp
POSTGRESQL_PORT_5432_TCP_ADDR=172.30.35.118
RABBITMQ_SERVICE_PORT=5672
RABBITMQ_PORT_5672_TCP_PROTO=tcp
CLOUDIGRADE_SERVICE_PORT=80
CLOUDIGRADE_PORT_80_TCP_PROTO=tcp
CLOUDIGRADE_PORT_80_TCP_ADDR=172.30.179.148
KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53
KUBERNETES_PORT_53_UDP_PROTO=udp
RABBITMQ_PORT_5672_TCP_PORT=5672
RABBITMQ_PORT_15672_TCP_PORT=15672
RABBITMQ_PORT_15672_TCP_ADDR=172.30.15.187
CLOUDIGRADE_SERVICE_PORT_NGINX=80
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_53_TCP_PORT=53
POSTGRESQL_PORT=tcp://172.30.35.118:5432
RABBITMQ_PORT_5672_TCP=tcp://172.30.15.187:5672
CLOUDIGRADE_SERVICE_HOST=172.30.179.148
HOME=/
```

Wow, that's a lot of environment variables! It looks like all the ones following this pattern for containers are auto-generated, and we may need to change the names of what cloudigrade is looking for to be more explicit and unique.

```
RABBITMQ_PORT_15672_TCP_ADDR=172.30.15.187
RABBITMQ_SERVICE_PORT_RABBITMQ_MANAGEMENT=15672
RABBITMQ_PORT=tcp://172.30.15.187:5672
RABBITMQ_PORT_15672_TCP=tcp://172.30.15.187:15672
RABBITMQ_SERVICE_PORT=5672
RABBITMQ_SERVICE_PORT_RABBITMQ=5672
RABBITMQ_PORT_5672_TCP_PROTO=tcp
RABBITMQ_PORT_15672_TCP_PROTO=tcp
RABBITMQ_PORT_5672_TCP=tcp://172.30.15.187:5672
RABBITMQ_PORT_5672_TCP_PORT=5672
RABBITMQ_SERVICE_HOST=172.30.15.187
RABBITMQ_PORT_5672_TCP_ADDR=172.30.15.187
RABBITMQ_HOST=rabbitmq-persistent.myproject.svc
RABBITMQ_PORT_15672_TCP_PORT=15672
```

**Comment by infinitewarp** [comment]
https://docs.openshift.com/online/dev_guide/environment_variables.html#automatically-added-environment-variables
