### ISSUE TITLE
`add_snapshot_ownership` signature changed unexpectedly

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#247]
I'm not sure when this broke because I know I've actually used this function successfully, but it's probably my own fault from all the refactoring I did recently. 😰 It looks like we changed the function signature for `aws.add_snapshot_ownership` to drop two of its arguments, but the call to it in `tasks.copy_ami_snapshot` was not updated.

### Steps to reproduce
1. `make oc-up-all`
1. `make user user-authenticate`
1. set local `AUTH` and `ARN` variables.
1. make sure the target ARN has a running EC2 instance
1. `http post http://cloudigrade-myproject.127.0.0.1.nip.io/api/v1/account/ "${AUTH}" account_arn="${ARN}" resourcetype=AwsAccount`
1. go to the latest deployment in openshift for cloudigrade-celery: https://127.0.0.1:8443/console/project/myproject/browse/dc/cloudigrade-celery
1. look at the logs

### Desired result

The task is picked up and runs normally without error.

### Actual result
```
[2018-05-01 20:09:05,181: ERROR/ForkPoolWorker-3] Task account.tasks.copy_ami_snapshot[72f6fcb4-abe1-4693-94c6-37cfd059be27] raised unexpected: TypeError('add_snapshot_ownership() takes 1 positional argument but 3 were given',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 155, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 48, in copy_ami_snapshot
    source_region
TypeError: add_snapshot_ownership() takes 1 positional argument but 3 were given
```

**Comment by infinitewarp** [comment]
I walked through the repro steps, and the tasks run successfully now. 👍
