### ISSUE TITLE
Pycurl library required to run celery.

### ISSUE THREAD

**Issue by ilyavw** [cloudigrade/cloudigrade#353]
## Summary

In trying to run celery locally I'm running into an unrecoverable error.

```
[2018-06-18 14:44:07,102: INFO/MainProcess] celery@iwhite-OSX.local ready.
[2018-06-18 14:44:07,103: CRITICAL/MainProcess] Unrecoverable error: ImportError('The curl client requires the pycurl library.',)
Traceback (most recent call last):
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/http/__init__.py", line 20, in get_client
    return hub._current_http_client
AttributeError: 'Hub' object has no attribute '_current_http_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 291, in create_loop
    item()
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/transport/SQS.py", line 316, in _schedule_queue
    queue, callback=promise(self._loop1, (queue,)),
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/transport/SQS.py", line 332, in _get_bulk_async
    return self._get_async(queue, maxcount, callback=callback)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/transport/SQS.py", line 342, in _get_async
    qname, count=count, connection=self.asynsqs,
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/transport/SQS.py", line 436, in asynsqs
    region=self.region
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/aws/sqs/connection.py", line 27, in __init__
    **kwargs
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/aws/connection.py", line 178, in __init__
    **http_client_params)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/aws/connection.py", line 151, in __init__
    self._httpclient = http_client or get_client()
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/http/__init__.py", line 22, in get_client
    client = hub._current_http_client = Client(hub, **kwargs)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/http/__init__.py", line 13, in Client
    return CurlClient(hub, **kwargs)
  File "/Users/iwhite/workspace/cloudigrade/cloudigrade/env/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 43, in __init__
    raise ImportError('The curl client requires the pycurl library.')
ImportError: The curl client requires the pycurl library.
[2018-06-18 14:44:07,109: INFO/MainProcess] beat: Shutting down...
```

## Steps to Reproduce

1. Have fresh env
2. Run celery `DJANGO_SETTINGS_MODULE=config.settings.local celery -l info -A config worker --beat             --scheduler django_celery_beat.schedulers:DatabaseScheduler             -Q copy_ami_snapshot,create_volume,enqueue_ready_volumes,scale_up_inspection_cluster,run_inspection_cluster`

## Expected Result

- Celery starts up

## Actual Result

- Celery crashes and burns 

## Additional context

`AWS_ACCESS_KEY_ID ,AWS_SECRET_ACCESS_KEY ,AWS_DEFAULT_REGION ,AWS_SQS_ACCESS_KEY_ID ,AWS_SQS_SECRET_ACCESS_KEY ,AWS_SQS_REGION ,AWS_SQS_QUEUE_NAME_PREFIX ,HOUNDIGRADE_ECS_CLUSTER_NAME ,HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME ,HOUNDIGRADE_AWS_AVAILABILITY_ZONE` are all set in the env.

**Comment by infinitewarp** [comment]
This was almost certainly caused by https://github.com/cloudigrade/cloudigrade/pull/342 for https://github.com/cloudigrade/cloudigrade/issues/339. There's a good chance we just need to bring pycurl back for Celery to work with SQS.

**Comment by ironfroggy** [comment]
I reproduced the original issue, and can confirm this fix.

**Comment by ilyavw** [comment]
I too can confirm that the issue is resolved, closing.

**Comment by hafsalrahman** [comment]
how this issue is solved, where is the solution?

**Comment by elyezer** [comment]
@hafsalrahman this repo is a read only copy of gitlab.com/cloudigrade/cloudigrade
