### ISSUE TITLE
Identify "OpenShift compute nodes" using AWS tags

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#381]
## Summary

As a Cloud Meter customer, I want my OpenShift compute nodes to be recognized by Cloud Meter so I can report its usage appropriately.

## Acceptance Criteria

- [ ] Verify that when cloudigrade processes the results from a houndigrade inspection of an image that is intended for OpenShift compute node use (as indicated by presence of a tag), cloudigrade looks at the image and records an "openshift" tag if necessary.
- [ ] Verify that when the customer adds or removes the "openshift" tag to an image _after_ we have already inspected it, the cloudigrade log analyzer recognizes that change and updates our record of the image with the appropriate addition or removal of tags.
    - Yes, we recognize that this potentially retroactively changes values we had reported.
- [ ] Verify that integration tests have been recorded as issues in github.

## Assumptions and Questions

- Are customers tagging images? Or instances?
    - The customer will be tagging the _images_.
- We want to look for the presence of a tag on the image with the tag name "cloudigrade-ocp-present". We do not care about the value of the tag; we only care whether or not the tag exists.
- We should be willing to make an educated guess _for now_ ("cloudigrade-ocp-present") and fix the correct name and value _later_ as needed.
    - Do we need to have an item tracked in Aha to talk with customers directly, find out if or what they are using for tags already, etc.? Maybe someone put a link here later if one exists.
    - Do we need to have per-clount tag definition? Not yet…

**Comment by infinitewarp** [comment]
After the latest merge to master, I'm getting a 500 error when I register a cloud account that has an instance running and the instance is from a marketplace image (the free RHEL one) that presumably has no tags.

You probably need to add a check that the tags attribute exists and `is not None` before iterating over it.

```
Traceback (most recent call last):
  File "/Users/brasmith/.virtualenvs/cloudigrade/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/brasmith/.virtualenvs/cloudigrade/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/Users/brasmith/.virtualenvs/cloudigrade/lib/python3.6/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/Users/brasmith/.virtualenvs/cloudigrade/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/Users/brasmith/.virtualenvs/cloudigrade/lib/python3.6/site-packages/rest_polymorphic/serializers.py", line 74, in create
    return serializer.create(validated_data)
  File "/Users/brasmith/projects/cloudigrade/cloudigrade/account/serializers.py", line 121, in create
    image)
  File "/Users/brasmith/projects/cloudigrade/cloudigrade/account/serializers.py", line 156, in add_openshift_tag
    tags['Key'] for tags in ec2_image.tags]
TypeError: 'NoneType' object is not iterable
```

**Comment by kholdaway** [comment]
PR with fix here --> https://github.com/cloudigrade/cloudigrade/pull/397

**Comment by kholdaway** [comment]
Demo video --> https://drive.google.com/drive/u/2/folders/1vd2Mu5ysQ51G9_ST6reEW0-1XWmxZu8p?ogsrc=32
