### ISSUE TITLE
500 on cloud account creation due to "Object of type 'AwsArn' is not JSON serializable"

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/cloudigrade#396]
## Summary

On attempt to create a cloud account, I receive a 500 server error.

## Steps to Reproduce

1. Attempt to create a cloud account

## Expected Result

- A 201 response

## Actual Result

- 500

## Additional context

I peeked in the cloudigrade logs and this is what I saw:
```
Unable to verify the policy action "cloudtrail:CreateTrail" due to CloudTrail not providing a DryRun option.
Unable to verify the policy action "cloudtrail:UpdateTrail" due to CloudTrail not providing a DryRun option.
Unable to verify the policy action "cloudtrail:PutEventSelectors" due to CloudTrail not providing a DryRun option.
Unable to verify the policy action "cloudtrail:DescribeTrails" due to CloudTrail not providing a DryRun option.
Unable to verify the policy action "cloudtrail:StartLogging" due to CloudTrail not providing a DryRun option.
Object of type 'AwsArn' is not JSON serializable
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'AwsArn' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_polymorphic/serializers.py", line 74, in create
    return serializer.create(validated_data)
  File "/opt/cloudigrade/account/serializers.py", line 112, in create
    arn, message['image_id'], message['region'])
  File "/opt/cloudigrade/account/util.py", line 188, in start_image_inspection
    copy_ami_snapshot.delay(arn, ami_id, region)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 745, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'AwsArn' is not JSON serializable
```

These logs are from pod `cloudigrade-api-260-h8j8n`on the test env from a integrade test run that ran a test trying to create a cloud account

**Comment by kdelee** [comment]
I can confirm bugfix for this, now this works and just the None type problem that the other PR #397 is for
