### ISSUE TITLE
Cloudigrade crashing, reporting "Bad Address"

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#427]
In GitLab by @elijahd on Jul 12, 2018, 10:09

## Summary

Cloudigrade appears to deploy, migrations are run, then while it is running it blows up.

## Steps to Reproduce

1. Deploy `master` branch cloudigrade

## Expected Result

- It runs!

## Actual Result

```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/cloudigrade/config/__init__.py", line 1, in <module>
    from config.celery import app as celery_app
  File "/opt/cloudigrade/config/celery.py", line 6, in <module>
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/__init__.py", line 16, in setup
    from django.urls import set_script_prefix
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
OSError: [Errno 14] Bad address
[2018-07-12 14:06:21 +0000] [314] [INFO] Worker exiting (pid: 314)
[2018-07-12 14:06:21 +0000] [320] [INFO] Booting worker with pid: 320
[2018-07-12 14:06:21 +0000] [214] [INFO] Worker exiting (pid: 214)
[2018-07-12 14:06:21 +0000] [188] [INFO] Worker exiting (pid: 188)
[2018-07-12 14:06:21 +0000] [41] [INFO] Worker exiting (pid: 41)
[2018-07-12 14:06:21 +0000] [196] [INFO] Worker exiting (pid: 196)
[2018-07-12 14:06:21 +0000] [295] [INFO] Worker exiting (pid: 295)
[2018-07-12 14:06:21 +0000] [285] [INFO] Worker exiting (pid: 285)
[2018-07-12 14:06:21 +0000] [303] [INFO] Worker exiting (pid: 303)
[2018-07-12 14:06:21 +0000] [293] [INFO] Worker exiting (pid: 293)
[2018-07-12 14:06:21 +0000] [305] [INFO] Worker exiting (pid: 305)
[2018-07-12 14:06:21 +0000] [307] [INFO] Worker exiting (pid: 307)
[2018-07-12 14:06:21 +0000] [308] [INFO] Worker exiting (pid: 308)
[2018-07-12 14:06:21 +0000] [311] [INFO] Worker exiting (pid: 311)
[2018-07-12 14:06:21 +0000] [312] [INFO] Worker exiting (pid: 312)
[2018-07-12 14:06:21 +0000] [316] [INFO] Worker exiting (pid: 316)
[2018-07-12 14:06:22 +0000] [319] [INFO] Worker exiting (pid: 319)
[2018-07-12 14:06:22 +0000] [320] [INFO] Worker exiting (pid: 320)
[2018-07-12 14:06:22 +0000] [13] [INFO] Shutting down: Master
[2018-07-12 14:06:22 +0000] [13] [INFO] Reason: Worker failed to boot.
```

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Jul 12, 2018, 10:09

assigned to @katherine-black

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 12, 2018, 10:14

changed the description

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Jul 16, 2018, 13:05

Just a note: all Integrade builds are currently blocked until some resolution is found on this ticket.

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Jul 17, 2018, 10:03

mentioned in merge request !426

**Comment by katherine-black** [comment]
In GitLab by @erezende on Jul 18, 2018, 09:57

Checked the two related Merge Requests and the solution is good for now. Since we don't have any AC items to verify on this issue I will just go ahead and close it.

**Comment by katherine-black** [comment]
In GitLab by @erezende on Jul 18, 2018, 09:57

closed
