### ISSUE TITLE
The log analyzer blows up when it tries to process messages. (possibly power off events)

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#446]
In GitLab by @elijahd on Jul 24, 2018, 16:49

## Summary

[cloudigrade-celery-1-vh5pj.log](/uploads/33184d1663254d203cb649c4e153a1d8/cloudigrade-celery-1-vh5pj.log)

The log analyzer blows up when it tries to process messages. (possibly power off events)

## Steps to Reproduce

1) Clean, running cloudigrade. No regular user accounts, one super user account. No cloud accounts.
2) Create regular user
3) Have regular user create account with aws account with 0 running instances. (I used dev07 for the customer account)
4) After account creation, power on 3 instances, each from a different image: 
* `'ami-0516697f4bb8af0b7'` : private shared centos
* `'ami-0bf18d6709ff12ee8'` : centos owned by account (dev07)
* `'ami-0011ab01eb7fb4fbc'` : marketplace fedora 28

5) Wait until "on" events are listed for the three instances at `/api/v1/event/`
6) Terminate the instances

My hypothesis is that the following traceback occurred when the log analyzer was attempting to process the "off" events from the CloudTrail-->s3-->sqs data flow. I'm guessing that terminated instances do not have a subnet. I say this because ostensibly, all the `power_on` events were already processed because I had waited until they showed up and there was no other activity on the account.

## Expected Result

- Messages are processed without errors
- off events are intelligible to the log analyzer

## Actual Result

```
Task analyzer.tasks.analyze_log[0adac38b-ece7-4a43-8888-14fbf9ce35b7] raised unexpected: IntegrityError('null value in column "subnet" violates not-null constraint\nDETAIL:  Failing row contains (7, null, t2.micro).\n',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
    return func(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
    self._pq_execute(self._query, conn._async)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
    self._pq_fetch()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
    raise self._conn._create_exception(cursor=self)
psycopg2cffi._impl.exceptions.IntegrityError: null value in column "subnet" violates not-null constraint
DETAIL:  Failing row contains (7, null, t2.micro).
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/analyzer/tasks.py", line 69, in analyze_log
    _save_results(instances)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/cloudigrade/analyzer/tasks.py", line 235, in _save_results
    data['events']
  File "/opt/cloudigrade/account/util.py", line 105, in save_instance_events
    event.save()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/polymorphic/models.py", line 83, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
    return func(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
    self._pq_execute(self._query, conn._async)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
    self._pq_fetch()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
    raise self._conn._create_exception(cursor=self)
django.db.utils.IntegrityError: null value in column "subnet" violates not-null constraint
DETAIL:  Failing row contains (7, null, t2.micro).
```

## Additional context

`SCALE_UP_INSPECTION_CLUSTER_SCHEDULE="300"`
I waited over an hour after the off event and still no off event was ever recorded. I take this as additional support that it was the off event that broke the log analyzer.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 24, 2018, 16:50

changed title from **The log analyzer blows up when it trie{-d-} to process messages. (possibly power off events)** to **The log analyzer blows up when it trie{+s+} to process messages. (possibly power off events)**

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Jul 25, 2018, 13:14

@elijahd did this instance actually have a subnet attached to it?

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 25, 2018, 17:04

I did no attaching of subnets. Can't say what the defaults are. Looks like from https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade/account/util.py#L102 it allways expects if to have a value for "subnet"

I saved all the json blobs in my bucket from today, I did run into this problem today, maybe you can find a candidate in these events?

https://drive.google.com/open?id=1MYvklryRs8y9pxORGKQ7JlWI-wo4pi-l

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 30, 2018, 09:39

https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade/analyzer/tasks.py#L111 creates a [boto3 EC2 Instance](https://boto3.readthedocs.io/en/latest/reference/services/ec2.html#instance) object, which can be made from a terminated instance ID without complaint, but not all methods/properties can be called.

Example:

```
In [42]: import boto3
    ...: r = boto3.Session().resource('ec2')
    ...: # create an Instance object for a terminated instance
    ...: inst = r.Instance('i-07229a02ee9f16909')
    ...: # show that it allows you to access the "subnet" property
    ...: # but that is a None type object
    ...: print(inst.subnet)
    ...: 
    ...: 

None


In [43]: print(inst.subnet_id)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-9aa61a7fb98e> in <module>()
----> 1 print(inst.subnet_id)

~/envs/cloudi/lib64/python3.6/site-packages/boto3/resources/factory.py in property_loader(self)
    343                             self.__class__.__name__))
    344 
--> 345             return self.meta.data.get(name)
    346 
    347         property_loader.__name__ = str(snake_cased)

AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by katherine-black** [comment]
In GitLab by @erezende on Aug 1, 2018, 10:16

Checked the database and the field is not optional which should prevent this bug to happen again. Time to close this issue.

**Comment by katherine-black** [comment]
In GitLab by @erezende on Aug 1, 2018, 10:16

closed

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 13:05

Looks like this is cropping up again!?  Terminated an instance on an account that test.cloudigra.de is tracking and seeing this in the celery logs:

```
raised unexpected: AttributeError("'NoneType' object has no attribute 'get'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/analyzer/tasks.py", line 62, in analyze_log
    instances = _parse_log_for_ec2_instance_events(log)
  File "/opt/cloudigrade/analyzer/tasks.py", line 117, in _parse_log_for_ec2_instance_events
    'subnet': data['instance_details'].subnet_id,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 13:05

reopened

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 13:34

going to open different bug...

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 13:34

closed
