### ISSUE TITLE
Task blows up and causes inspection process to hang on marketplace image

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#448]
In GitLab by @elijahd on Jul 25, 2018, 16:56

## Summary

Unhandled error causes inspection process to hang indefinitely.

## Steps to Reproduce

1. Stand up clean cloudigrade
1. Create user
1. Create cloud account for user with no instances
1. Launch an instance from the ami `ami-077b0e78`
1. Watch celery logs

## Expected Result

- Cloudigrade figures out it is a marketplace image and marks it as inspected and moves on

## Actual Result

- Cloudigrade breaks, and if there are any other instances, it appears to cause indefinite hang on all inspection.

## Additional context

I used dev07 to reproduce this. Originally came across it when launching multiple instances from several AMIs, then reproduced it with running just the one instance.

Logs:

```
[2018-07-25 20:49:27,464: ERROR/ForkPoolWorker-2] Task account.tasks.copy_ami_to_customer_account[2d2a3272-19ac-4465-974d-917384ab741c] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.",)
Traceback (most recent call last):
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 166, in copy_ami_to_customer_account
    raise e
  File "/opt/cloudigrade/account/tasks.py", line 152, in copy_ami_to_customer_account
    new_ami_id = aws.copy_ami(session, reference_ami.id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 145, in copy_ami
    SourceRegion=source_region,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
RuntimeError: Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 25, 2018, 17:02

FYI also ended up with same errors as #439 in this run as well

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 1, 2018, 16:31

I am working on verifying this...:turtle: slowly but surely

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 3, 2018, 13:10

:heavy\_check\_mark:

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 3, 2018, 13:10

closed
