### ISSUE TITLE
'TerminateInstances' event not interpreted as a 'power_off' event

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#449]
In GitLab by @elijahd on Jul 27, 2018, 13:05

## Summary

Instances can be stopped or they can be terminated. Events that CloudTrail may report that indicate that an instance was told to stop or terminate include (but may not be limited to):

```
StopInstance
StopInstances
TerminateInstanceInAutoScalingGroup
TerminateInstances
```

When I terminated an instance with `TerminateInstances` via a boto3 call, the event was recorded by CloudTrail in the s3 bucket that my cloudigrade was looking at, but no `'power_off'` event was ever recorded. I also tried using `StopInstances` via the aws web UI, and this WAS recorded as a `'power_off'` event, so I know that `TerminateInstances` was treated differently than `StopInstances`.

## Steps to Reproduce

1. Create a user
1. Create a cloud account
1. Start an instance
1. Wait for the `power_on` event to get recorded at `/api/v1/event/` for that instance
1. **Terminate** the instance with boto or aws cli or aws ui
1. Wait until the `TerminateInstances` event is recorded by CloudTrail into cloudigrade's s3 bucket.
1. Wait for the log analyzer to run
1. Observe that no `'power_off'` event is recorded.

## Expected Result

- However instances stop or are terminated, a power off event is recorded so when usage reports are created, they accurately reflect my usage.

## Actual Result

- No `'power_off'` event is recorded and my usage reports will be inaccurate.

## Additional context

Ping me for the json blobs from the creation and stopping and terminating of instances.[stop-vs-terminate-json.zip](/uploads/bac43b0f75d0450c5c4f12fe48d5c41a/stop-vs-terminate-json.zip)

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 27, 2018, 14:30

The attached json describe 4 cloudtrail events. The 1st instance powered on was terminated. The power on event was recorded, but no power off event was recorded. Then I powered on a new instance, and after receiving the power on event, I "stopped" it via the web UI. The power off event for this instances was recorded. Here are the events as I saw them from the API of cloudigrade:

```
[{'event_type': 'power_on',
  'id': 1,
  'instance': 'http://cloudigrade.127.0.0.1.nip.io/api/v1/instance/1/',
  'instance_type': 't2.micro',
  'machineimage': 'http://cloudigrade.127.0.0.1.nip.io/api/v1/image/1/',
  'occurred_at': '2018-07-27T15:38:35Z',
  'resourcetype': 'AwsInstanceEvent',
  'subnet': 'subnet-e501d4cb'},
 {'event_type': 'power_on',
  'id': 19,
  'instance': 'http://cloudigrade.127.0.0.1.nip.io/api/v1/instance/2/',
  'instance_type': 't2.micro',
  'machineimage': 'http://cloudigrade.127.0.0.1.nip.io/api/v1/image/1/',
  'occurred_at': '2018-07-27T16:24:06Z',
  'resourcetype': 'AwsInstanceEvent',
  'subnet': 'subnet-6aed2636'},
 {'event_type': 'power_off',
  'id': 25,
  'instance': 'http://cloudigrade.127.0.0.1.nip.io/api/v1/instance/2/',
  'instance_type': 't2.micro',
  'machineimage': 'http://cloudigrade.127.0.0.1.nip.io/api/v1/image/1/',
  'occurred_at': '2018-07-27T16:41:27Z',
  'resourcetype': 'AwsInstanceEvent',
  'subnet': 'subnet-6aed2636'}]
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 27, 2018, 14:50

I think this is probably related to #439 . 

The message with the `TerminateInstances` event (439727791560_CloudTrail_us-east-1_20180727T1555Z_NOvuzsukkdTp6Rl7-terminate-instances.json in the archive) is shown as being `in flight` and the "receive count" is 48 and increasing. The celery logs keep showing the following stack trace when I presume it is attempting to process this event:

```
[2018-07-27 18:45:55,522: ERROR/ForkPoolWorker-3] Task analyzer.tasks.analyze_log[99a55490-510d-49ac-80ba-7eac241d5271] raised unexpected: AttributeError("'NoneType' object has no attribute 'get'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/analyzer/tasks.py", line 65, in analyze_log
    instances = _parse_log_for_ec2_instance_events(log)
  File "/opt/cloudigrade/analyzer/tasks.py", line 120, in _parse_log_for_ec2_instance_events
    'subnet': data['instance_details'].subnet_id,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
```

The fact that it keeps getting received and has not been ack'd makes me think that #440 is probably because events are not ack'd until they have been processed, and this is what makes celery pick up the messages multiple times and duplicate events.

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Jul 31, 2018, 15:27

@elijahd Can not reproduce, likely fixed as part of https://gitlab.com/cloudigrade/cloudigrade/issues/439.

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Jul 31, 2018, 15:28

![image](https://my-gitlab-bucket.s3.amazonaws.com/118967787/2054cf48c68a0de66623ef23e7e20421.png)

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Jul 31, 2018, 17:20

closed
