### ISSUE TITLE
User receives 500 error without useful info if cloud trail setup fails

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#460]
In GitLab by @elijahd on Aug 7, 2018, 11:26

## Summary

If problems occur with the CloudTrail creation upon cloud account creation in cloudigrade, the user may get a 500 error that does not tell them much about what went wrong.

### Scenario 1: If customers happen to be using the CloudTrail service themselves, we may run into a limit of how many cloudtrails are allowed on an account. 

1. Create 5 cloud trails on an account with unique names (this is a limit set on our accounts on a per-region basis, it may be configurable to a lower number).
1. Attempt to register the account as a cloud account on cloudigrade

### Scenario 2: If cloudigrade is configured to have some bad cloudtrail name that AWS does not like, things blow up.

1. Configure cloudigrade to have a cloudtrail name that is less than 3 characters or more than 63 and deploy
1. Attempt to create a cloud account for a user

### Scenario 3: Anything else bad happens when talking to AWS

... Basically if an exception is raised from talking to AWS during cloud account creation, it blows up and no information is surfaced to the user.

## Expected Result

- If we cannot create a a CloudTrail, the user gets a useful message so they can do something about the problem.

## Actual Result

500 error with message `'A server error occurred.'`

```
E           ============================================================
E           request path : '/api/v1/account/'
E           
E           request body : (b'{"account_arn": "arn:aws:iam::439727791560:role/allow-dev11-cloudigrade-metering", "resourcetype": "AwsAccount"}')
E           
E           request headers : {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '112', 'Content-Type': 'application/json', 'Authorization': '********'}
E           
E           response code : 500
E           
E           json_error_message : {'detail': 'A server error occurred.'}
E           ============================================================
```

## Additional context

To resolve this, I think we should return some more information to the user. The traceback in the shows that we probably have enough information to pass along to the user so they can fix the problem and come back to register the account later:

```
An error occurred (MaximumNumberOfTrailsExceededException) when calling the CreateTrail operation: User: 439727791560 already has 5 trails in us-east-1.
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_polymorphic/serializers.py", line 74, in create
    return serializer.create(validated_data)
  File "/opt/cloudigrade/account/serializers.py", line 110, in create
    aws.configure_cloudtrail(session, aws_account_id)
  File "/opt/cloudigrade/util/aws/cloudtrail.py", line 30, in configure_cloudtrail
    response = create_cloudtrail(cloudtrail, name)
  File "/opt/cloudigrade/util/aws/cloudtrail.py", line 91, in create_cloudtrail
    raise e
  File "/opt/cloudigrade/util/aws/cloudtrail.py", line 87, in create_cloudtrail
    IsMultiRegionTrail=True,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MaximumNumberOfTrailsExceededException: An error occurred (MaximumNumberOfTrailsExceededException) when calling the CreateTrail operation: User: 439727791560 already has 5 trails in us-east-1.
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 8, 2018, 11:07

Reproduced this via the web UI, same traceback in the cloudigrade-api pod logs and this is what the error would look like to the user:

![too_many_cloudtrails_500_error](/uploads/af67a627e2e8cbcd5b57219369b51c2b/too_many_cloudtrails_500_error.png)

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 8, 2018, 16:30

changed title from **User receives 500 error without useful info if cloud trail setup fails{- because of too many existing cloud trails-}** to **User receives 500 error without useful info if cloud trail setup fails**

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 8, 2018, 16:49

This also comes up from other unexpected exceptions at cloud account registration time. 

For example, we ran into a problem with the name of our CloudTrail where the cloudigrade container had the following traceback:

```
An error occurred (InvalidS3BucketNameException) when calling the CreateTrail operation: Bucket name should be between 3 and 63 characters long: integrade-review-check-crea-bltr92integrade-review-check-crea-bltr92-s3
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_polymorphic/serializers.py", line 74, in create
    return serializer.create(validated_data)
  File "/opt/cloudigrade/account/serializers.py", line 110, in create
    aws.configure_cloudtrail(session, aws_account_id)
  File "/opt/cloudigrade/util/aws/cloudtrail.py", line 30, in configure_cloudtrail
    response = create_cloudtrail(cloudtrail, name)
  File "/opt/cloudigrade/util/aws/cloudtrail.py", line 90, in create_cloudtrail
    raise e
  File "/opt/cloudigrade/util/aws/cloudtrail.py", line 86, in create_cloudtrail
    IsMultiRegionTrail=True,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidS3BucketNameException: An error occurred (InvalidS3BucketNameException) when calling the CreateTrail operation: Bucket name should be between 3 and 63 characters long: integrade-review-check-crea-bltr92integrade-review-check-crea-bltr92-s3

```

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Aug 17, 2018, 14:43

Resolved in !469

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Aug 17, 2018, 14:46

@elijahd your comment should be a separate bug, as thats a completely different issue (cloudtrail name too long), it should be captured separate from this issue.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 20, 2018, 10:14

Closing because the original issue here was a duplicate of #462.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 20, 2018, 10:14

closed
