### ISSUE TITLE
Worker dying appears to cause account.tasks.copy_ami_snapshot to bail and inspection does not complete

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#461]
In GitLab by @elijahd on Aug 7, 2018, 16:38

## Summary

Inspection of image gets stuck in `pending` state. Appears to be because of a working getting sent `SIGKILL`.

## Steps to Reproduce

1. Start an instance based off of `'ami-0bf18d6709ff12ee8'` in the dev07 account
1. Create a cloud account pointing to this aws account
1. Watch celery logs

## Expected Result

- Inspection completes

## Actual Result

- Inspection gets stuck in pending. Looks like it is because of this worker getting killed:

```
[2018-08-07 15:24:21,960: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[ae4f7e3d-a573-40f4-9ba1-2c33b3c6e2e8]  
[2018-08-07 15:24:21,972: INFO/ForkPoolWorker-6] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:22,075: INFO/ForkPoolWorker-6] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:22,268: INFO/ForkPoolWorker-6] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:22,357: INFO/ForkPoolWorker-6] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:22,508: INFO/ForkPoolWorker-6] AWS snapshot "snap-0e4592a08b31e87d3" for image "ami-759bc50a" has owner "099720109477"; current session is account "439727791560"
[2018-08-07 15:24:22,510: INFO/ForkPoolWorker-6] Resetting dropped connection: queue.amazonaws.com
[2018-08-07 15:24:22,604: INFO/ForkPoolWorker-6] Task account.tasks.copy_ami_snapshot[ae4f7e3d-a573-40f4-9ba1-2c33b3c6e2e8] succeeded in 0.6363074879627675s: None
[2018-08-07 15:24:22,626: INFO/MainProcess] Received task: account.tasks.copy_ami_to_customer_account[cae6fb37-25a4-4348-bd19-93d16d7c4ab8]  
[2018-08-07 15:24:22,649: INFO/ForkPoolWorker-8] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:22,876: INFO/ForkPoolWorker-8] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:23,066: INFO/ForkPoolWorker-8] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:23,140: INFO/ForkPoolWorker-8] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:23,779: INFO/ForkPoolWorker-8] Resetting dropped connection: queue.amazonaws.com
[2018-08-07 15:24:23,846: INFO/ForkPoolWorker-8] Task account.tasks.copy_ami_to_customer_account[cae6fb37-25a4-4348-bd19-93d16d7c4ab8] succeeded in 1.202905258978717s: None
[2018-08-07 15:24:23,870: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[160550ac-1471-41f6-954f-e9e7c37eac34]  
[2018-08-07 15:24:23,884: INFO/ForkPoolWorker-2] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:23,987: INFO/ForkPoolWorker-2] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:24,183: INFO/ForkPoolWorker-2] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:24,391: INFO/ForkPoolWorker-2] ImageNotReadyException: Image ami-041b8f091f48e3bc3 has state pending (reason: None)
[2018-08-07 15:24:24,393: INFO/ForkPoolWorker-2] Resetting dropped connection: queue.amazonaws.com
[2018-08-07 15:24:24,439: INFO/ForkPoolWorker-2] Task account.tasks.copy_ami_snapshot[160550ac-1471-41f6-954f-e9e7c37eac34] retry: Retry in 1s: ImageNotReadyException('Image ami-041b8f091f48e3bc3 has state pending (reason: None)',)
[2018-08-07 15:24:25,525: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[160550ac-1471-41f6-954f-e9e7c37eac34]  ETA:[2018-08-07 15:24:25.392187+00:00] 
[2018-08-07 15:24:26,420: INFO/ForkPoolWorker-4] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:26,538: INFO/ForkPoolWorker-4] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:26,681: INFO/ForkPoolWorker-4] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-07 15:24:26,778: INFO/ForkPoolWorker-4] ImageNotReadyException: Image ami-041b8f091f48e3bc3 has state pending (reason: None)
[2018-08-07 15:24:26,780: INFO/ForkPoolWorker-4] Resetting dropped connection: queue.amazonaws.com
[2018-08-07 15:24:26,821: INFO/ForkPoolWorker-4] Task account.tasks.copy_ami_snapshot[160550ac-1471-41f6-954f-e9e7c37eac34] retry: Retry in 0s: ImageNotReadyException('Image ami-041b8f091f48e3bc3 has state pending (reason: None)',)
[2018-08-07 15:24:27,477: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[160550ac-1471-41f6-954f-e9e7c37eac34]  
[2018-08-07 15:24:27,487: INFO/ForkPoolWorker-6] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:27,569: INFO/ForkPoolWorker-6] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-07 15:24:27,870: ERROR/MainProcess] Process 'ForkPoolWorker-6' pid:21 exited with 'signal 9 (SIGKILL)'
[2018-08-07 15:24:27,882: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

After that no mention of the snapshot/any progress in getting the volume ready for houndigrade to inspect is present in the logs.

## Additional context

This happened to me 3 times in a row with fresh deploys on OSD in the `cloudigrade-review` project, not on my local openshift.

This blocks being able to test inspection on gitlab-ci.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 8, 2018, 14:59

To further investigate this, I created an account on test.cloudigra.de

I created the following instances:
```
i-08f57804410734024 from LOCAL_CENTOS7_XFS_OPENSHIFT (ami-067e15718a7a1ed0a)
launch time August 8, 2018 at 1:02:54 PM UTC-4
terminated at August 8, 2018 at 1:12:00 PM UTC-4

i-09f905a808748efc7 from AMI ID LOCAL_CENTOS7_LVM (ami-0f4ef4df59416d9ab)
launch time August 8, 2018 at 1:02:54 PM UTC-4
terminated at 2:44 August 8, 2018 at 2:44:54 PM UTC-4

i-01b6d5b1c7c60bf18 from LOCAL_RHEL7_LVM_OPENSHIFT (ami-053b2eeaaa6d13a24)
launch time August 8, 2018 at 1:56:02 PM UTC-4
terminated at 2:44 August 8, 2018 at 2:44:54 PM UTC-4

 
i-006bbfc56a0e385e3 from Pygoscelis-Papua_Gentoo_32-bit-EBS-2014-04-16-02-20-38 (ami-036e776a)
launch time August 8, 2018 at 2:20:59 PM UTC-4
terminated at 2:44 August 8, 2018 at 2:44:54 PM UTC-4

 
i-0752b105e799074ee from LOCAL_RHEL7_XFS (ami-09f630ec35588bec4)
launch time August 8, 2018 at 2:23:07 PM UTC-4 (less than one hour)
terminated at 2:44 August 8, 2018 at 2:44:54 PM UTC-4
```

As cloudigrade discovered them through events, I observed the memory usage growing:
![celery_memory_leak_during_copy_process](/uploads/725197b869c5a90744705bf5cdb2d454/celery_memory_leak_during_copy_process.png)

Then as it discovered and started the copy process for the last image, it blew up with a Bad Address read. Then it started to **seem** to function normally. Still waiting to see what happens, but something is going on with memory consumption for sure.
[cloudigrade-celery-7-zb89z__1_.log](/uploads/293377031dd842627c93ca1adb71e566/cloudigrade-celery-7-zb89z__1_.log)

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Aug 8, 2018, 16:20

I think the number of celery workers running in the pod is immediately starting us with a really low ceiling of working memory, tho they are entirely unwarranted with limited RAM and CPU resources. I don't see that this is being configured explicitly, so unless I overlooked are we just using the Celery defaults?

If we can make it configurable, we could lower the resource requirements for the celery workers on test environment significantly.

The tracebacks shared suggest that, on top of the usage from the baseline Celery workers, multiprocessing pools are being initialized which push us over the top. Oops!

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 9, 2018, 09:18

Today I checked back on the inspection state of these images. All but 1 reached the "inspected" state. The one that is still reporting as "preparing for inspection" is from the following instance:

```
i-006bbfc56a0e385e3 from Pygoscelis-Papua_Gentoo_32-bit-EBS-2014-04-16-02-20-38 (ami-036e776a)
launch time August 8, 2018 at 2:20:59 PM UTC-4
terminated at 2:44 August 8, 2018 at 2:44:54 PM UTC-4
```

Reading the logs it appears this is the image (or rather, the parent to the image) that was being worked on (by `account.tasks.copy_ami_snapshot` when the OOM event occurred. `ami-036e776a` is a community AMI, so it got copied to the customer account as `ami-0dd49fd28aa4ca609` with AMI Name: `cloudigrade reference copy (Pygoscelis-Papua_Gentoo_32-bit-EBS-2014-04-16-02-20-38)` and Source: `311230538223/cloudigrade reference copy (Pygoscelis-Papua_Gentoo_32-bit-EBS-2014-04-16-02-20-38)`. Then `ami-0dd49fd28aa4ca609` was getting copied to the cloudigrade account when the OOM happened.


*Discovered snapshot from `ami-036e776a` is not owned by customer*
```
[2018-08-08 18:29:39,061: INFO/ForkPoolWorker-3] AWS snapshot "snap-84be0d58" for image "ami-036e776a" has owner "902460189751"; current session is account "311230538223"
[2018-08-08 18:29:39,063: INFO/ForkPoolWorker-3] Resetting dropped connection: queue.amazonaws.com
```
*Start task `account.tasks.copy_ami_to_customer_account` to copy to customer acccount*
```
[2018-08-08 18:29:39,261: INFO/ForkPoolWorker-3] Task account.tasks.copy_ami_snapshot[b6e8f0a4-a744-44c4-86d7-bba92e240fce] succeeded in 1.2947986300569028s: None
[2018-08-08 18:29:39,261: INFO/MainProcess] Received task: account.tasks.copy_ami_to_customer_account[ea3effab-1625-47c1-9948-ab7eb0773bb5]  
[2018-08-08 18:29:39,273: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:39,868: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:40,170: ERROR/MainProcess] Process 'ForkPoolWorker-10' pid:5358 exited with 'signal 9 (SIGKILL)'
[2018-08-08 18:29:40,270: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:40,561: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:41,570: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): queue.amazonaws.com
[2018-08-08 18:29:41,861: INFO/ForkPoolWorker-12] Task account.tasks.copy_ami_to_customer_account[ea3effab-1625-47c1-9948-ab7eb0773bb5] succeeded in 2.5934955270495266s: None
```

*Now that `ami-0dd49fd28aa4ca609` is in customer account, copy that to cloudigrade*
```
[2018-08-08 18:29:41,862: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51]  
[2018-08-08 18:29:41,876: INFO/ForkPoolWorker-11] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:42,168: INFO/ForkPoolWorker-11] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:42,767: INFO/ForkPoolWorker-11] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:42,941: INFO/ForkPoolWorker-11] ImageNotReadyException: Image ami-0dd49fd28aa4ca609 has state pending (reason: None)
[2018-08-08 18:29:42,962: INFO/ForkPoolWorker-11] Resetting dropped connection: queue.amazonaws.com
[2018-08-08 18:29:43,087: INFO/ForkPoolWorker-11] Task account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51] retry: Retry in 1s: ImageNotReadyException('Image ami-0dd49fd28aa4ca609 has state pending (reason: None)',)
[2018-08-08 18:29:43,861: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51]  ETA:[2018-08-08 18:29:43.960766+00:00] 
[2018-08-08 18:29:43,966: INFO/ForkPoolWorker-13] Found credentials in environment variables.
[2018-08-08 18:29:44,072: INFO/ForkPoolWorker-13] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:44,465: INFO/ForkPoolWorker-13] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:45,071: INFO/ForkPoolWorker-13] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:45,262: INFO/ForkPoolWorker-13] ImageNotReadyException: Image ami-0dd49fd28aa4ca609 has state pending (reason: None)
[2018-08-08 18:29:45,468: INFO/ForkPoolWorker-13] Starting new HTTPS connection (1): queue.amazonaws.com
[2018-08-08 18:29:45,761: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51]  ETA:[2018-08-08 18:29:47.263884+00:00] 
[2018-08-08 18:29:45,762: INFO/ForkPoolWorker-13] Task account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51] retry: Retry in 2s: ImageNotReadyException('Image ami-0dd49fd28aa4ca609 has state pending (reason: None)',)
[2018-08-08 18:29:47,271: INFO/ForkPoolWorker-3] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:47,568: INFO/ForkPoolWorker-3] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:47,964: INFO/ForkPoolWorker-3] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:48,141: INFO/ForkPoolWorker-3] ImageNotReadyException: Image ami-0dd49fd28aa4ca609 has state pending (reason: None)
[2018-08-08 18:29:48,176: INFO/ForkPoolWorker-3] Task account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51] retry: Retry in 0s: ImageNotReadyException('Image ami-0dd49fd28aa4ca609 has state pending (reason: None)',)
[2018-08-08 18:29:48,261: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51]  
[2018-08-08 18:29:48,279: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:48,567: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:48,962: INFO/ForkPoolWorker-12] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2018-08-08 18:29:49,065: INFO/ForkPoolWorker-12] ImageNotReadyException: Image ami-0dd49fd28aa4ca609 has state pending (reason: None)
[2018-08-08 18:29:49,161: INFO/MainProcess] Received task: account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51]  ETA:[2018-08-08 18:29:57.065612+00:00] 
[2018-08-08 18:29:49,162: INFO/ForkPoolWorker-12] Task account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51] retry: Retry in 8s: ImageNotReadyException('Image ami-0dd49fd28aa4ca609 has state pending (reason: None)',)
[2018-08-08 18:29:50,080: INFO/Beat] Writing entries...
[2018-08-08 18:29:57,070: INFO/ForkPoolWorker-11] Starting new HTTPS connection (1): sts.amazonaws.com
[2018-08-08 18:29:57,268: INFO/ForkPoolWorker-11] Starting new HTTPS connection (1): sts.amazonaws.com
```

*Copying to cloudigrade account was still not complete when the error occurred*
```
[2018-08-08 18:29:57,761: ERROR/ForkPoolWorker-11] Task account.tasks.copy_ami_snapshot[29eaeeb0-161b-472c-bde5-cf4863dffe51] raised unexpected: OSError(14, 'Bad address')
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 52, in copy_ami_snapshot
    ami = aws.get_ami(session, ami_id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 106, in get_ami
    image = session.resource('ec2', region_name=source_region).Image(image_id)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/session.py", line 885, in create_client
    client_config=config, api_version=api_version)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 69, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 102, in _load_service_model
    api_version=api_version)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/loaders.py", line 383, in load_service_model
    model = self.load_data(full_path)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/loaders.py", line 420, in load_data
    found = self.file_loader.load_file(possible_path)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/loaders.py", line 173, in load_file
    payload = fp.read().decode('utf-8')
OSError: [Errno 14] Bad address
[2018-08-08 18:29:57,762: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:19 exited with 'signal 9 (SIGKILL)'
```

Now today, about 18 hours later, all other images are inspected and this one is still marked as `preparing`. I think it probably will stay stuck there.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 9, 2018, 10:12

Summary from standup:

1) Make number of celery workers configurable -- prefer a small number (like 1).
2) Make concurrency that celery works use configurable -- prefer a small number (like 1)
3) Potentially change amount of memory that celery pod has
4) Potentially spawn more celery pods instead of increasing concurrency/number of workers in production

Currently it looks like there are ~ 11 celery processes running in a pod "at rest" (only running the `analyzer.tasks.analyze_log` task and the pod is using ~ 400Mib of memory (out of 512).

```
sh-4.2$ ps auxww | grep 'celery' | grep -v grep | awk '{print $2}'
1
13
17
18
19
20
21
22
23
24
25
```

Also, may need to think about a different way of handling the tasks. The fact that the `copy_ami_snapshot` task fails and then is never picked up again/we never know about it is problematic.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 15:34

closed

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 16:59

filed https://gitlab.com/cloudigrade/cloudigrade/issues/458 to keep track of bigger problem
