### ISSUE TITLE
Some instances don't have all properties and this breaks the log analyzer

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#464]
In GitLab by @elijahd on Aug 10, 2018, 13:37

## Summary

A message is getting into the queue that is throwing an exception

## Steps to Reproduce

1. This is a bit unclear, as there are 192 messages on the queue and can't find which one it is yet. I hypothisize that it is a `TerminateInstances` event because terminated instances don't have a subnet when you create a `boto3.EC2.Instance` from them.

## Expected Result

- Log analyzer parses messages

## Actual Result

```
raised unexpected: AttributeError("'NoneType' object has no attribute 'get'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/analyzer/tasks.py", line 62, in analyze_log
    instances = _parse_log_for_ec2_instance_events(log)
  File "/opt/cloudigrade/analyzer/tasks.py", line 117, in _parse_log_for_ec2_instance_events
    'subnet': data['instance_details'].subnet_id,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

## Additional context

This is from `test.cloudigra.de` using the `rh-doppler` AWS account, you can find messages in the S3 bucket there.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 13:48

Looks like a related traceback:

```
[2018-08-10 19:14:42,568: ERROR/ForkPoolWorker-3] Task analyzer.tasks.analyze_log[c3ed2f32-ea40-4f97-b28b-7aa2c21958a3] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-015a3ec20413f8ca9' does not exist",)
Traceback (most recent call last):
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/analyzer/tasks.py", line 67, in analyze_log
    instances = _parse_log_for_ec2_instance_events(log)
  File "/opt/cloudigrade/analyzer/tasks.py", line 122, in _parse_log_for_ec2_instance_events
    'subnet': data['instance_details'].subnet_id,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-015a3ec20413f8ca9' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
```

Here is the message that is causing this error:
[977153484089_CloudTrail_us-east-1_20180802T1755Z_HfZk5zSGVojp3WbC.json](/uploads/68ae8a0e7f46d1100870c5cc7e77edc5/977153484089_CloudTrail_us-east-1_20180802T1755Z_HfZk5zSGVojp3WbC.json)

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 13:52

changed title from **Some instances don't have all properties and {-breaks-} log analyzer** to **Some instances don't have all properties and {+the breaks the+} log analyzer**

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 14:05

changed title from **Some instances don't have all properties and th{-e-} breaks the log analyzer** to **Some instances don't have all properties and th{+is+} breaks the log analyzer**

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 10, 2018, 14:55

Here are two messages that are raising exceptions like the 1st one (`AttributeError: 'NoneType' object has no attribute 'get'`)

[977153484089_CloudTrail_us-east-1_20180806T1430Z_tIBsAvnck1q35L5x.json](/uploads/49aaa086a9cf43e04992a507d2612997/977153484089_CloudTrail_us-east-1_20180806T1430Z_tIBsAvnck1q35L5x.json)

[977153484089_CloudTrail_us-east-1_20180803T2110Z_ViSTzsytuQkNOcA7.json](/uploads/14c2a759bc4dec8600277cd37f98c5c4/977153484089_CloudTrail_us-east-1_20180803T2110Z_ViSTzsytuQkNOcA7.json))

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 13, 2018, 10:49

I'm assigning myself to this one, but I'm not immediately jumping on a fix yet. The changes I'm making for https://gitlab.com/cloudigrade/cloudigrade/issues/412 are modifying code around the line referenced by that exception, and I may do some cleaner handling there.

**Comment by katherine-black** [comment]
In GitLab by @kholdaway on Aug 23, 2018, 11:37

closed
