### ISSUE TITLE
Failures during image preparation can lead to image stuck in "preparing" state

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#465]
In GitLab by @elijahd on Aug 10, 2018, 16:58

## Summary

If an un-handled problem occurs during image preparation, an image can get stuck in the preparing state and never proceed to inspection. There is currently no process to put images back in the queue to get inspected. 

## Reproducing scenarios

1. https://gitlab.com/cloudigrade/cloudigrade/issues/454 led to this type of problem because one of the tasks perparing the image was killed
1. Encountering unhandled AWS errors may also cause problems like this, see the following excerpt from celery logs:

```
[2018-08-10 19:16:08,041: ERROR/ForkPoolWorker-3] Task account.tasks.remove_snapshot_ownership[af5c135b-4084-478f-9223-2f442ccf5a15] raised unexpected: AwsSnapshotError('Snapshot snap-09029160bfa0d54d7 has state error at 0%',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 198, in remove_snapshot_ownership
    aws.check_snapshot_state(snapshot_copy)
  File "/opt/cloudigrade/util/aws/ec2.py", line 345, in check_snapshot_state
    raise AwsSnapshotError(message)
util.exceptions.AwsSnapshotError: Snapshot snap-09029160bfa0d54d7 has state error at 0%
[2018-08-10 19:16:08,043: INFO/MainProcess] Resetting dropped connection: queue.amazonaws.com
[2018-08-10 19:16:08,241: ERROR/ForkPoolWorker-2] Task account.tasks.create_volume[55302187-2604-48ce-a22e-8dd8def428c8] raised unexpected: AwsSnapshotError('Snapshot snap-09029160bfa0d54d7 has state error at 0%',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 235, in create_volume
    volume_id = aws.create_volume(snapshot_copy_id, zone)
  File "/opt/cloudigrade/util/aws/ec2.py", line 330, in create_volume
    check_snapshot_state(snapshot)
  File "/opt/cloudigrade/util/aws/ec2.py", line 345, in check_snapshot_state
    raise AwsSnapshotError(message)
util.exceptions.AwsSnapshotError: Snapshot snap-09029160bfa0d54d7 has state error at 0%
```

## Expected Result

- If something goes wrong while preparing the image, it can recover and will eventually get inspected

## Actual Result

- An image can remain in the `preparing` state indefinitely 

## Additional context

The OOM problem was worked around with a configuration change to celery ( see https://gitlab.com/cloudigrade/shiftigrade/merge_requests/53 ), but the core issue is that if something goes wrong, we 1) have no way of knowing except conjecture if a image seems to be staying in `preparing` for many houndigrade cycles and 2) have no remediation in place to deal with images that got forgotten.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Nov 27, 2018, 14:47

Since we have not seen this inspection problem come up again in recent months, I'm closing this issue.

That being said... we may add user stories soon to enable forcing re-inspection of images and to periodically check for failed inspections.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Nov 27, 2018, 14:47

closed
