### ISSUE TITLE
Private shared image cannot always be scanned by cloudigrade due to permissions

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#470]
In GitLab by @kholdaway on Aug 17, 2018, 19:26

## Summary

Private shared image cannot always be scanned by cloudigrade due to permissions.  This likely is a large change (story not bug)

## Steps to Reproduce

1. Create an AMI in account 1.  
2. Share AMI with account 2 but do not check the `Add "create volume" permissions to the following associated snapshots when creating permissions` checkbox.
3. Create an EC2 instance in account 2 using this AMI
4. Add account 2 to cloudigrade via the account API

## Expected Result
The image will scan successfully.  At a minimum mark this image state to indicate what happened.  The model stays in the `preparing for inspection` state.

## Actual Result
Cloudigrade fails to copy snapshot with this error.

```
[2018-08-17 22:49:25,684: ERROR/ForkPoolWorker-3] Task account.tasks.copy_ami_to_customer_account[72bb05bd-bc98-495e-8db6-75e9c921b361] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami",)
Traceback (most recent call last):
  File "/Users/kholdawa/dev/doppler/cloudigrade/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/Users/kholdawa/dev/doppler/cloudigrade/cloudigrade/account/tasks.py", line 169, in copy_ami_to_customer_account
    raise e
  File "/Users/kholdawa/dev/doppler/cloudigrade/cloudigrade/account/tasks.py", line 151, in copy_ami_to_customer_account
    new_ami_id = aws.copy_ami(session, reference_ami.id, snapshot_region)
  File "/Users/kholdawa/dev/doppler/cloudigrade/cloudigrade/util/aws/ec2.py", line 183, in copy_ami
    SourceRegion=source_region,
  File "/Users/kholdawa/.local/share/virtualenvs/cloudigrade-DXtd7Emz/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/kholdawa/.local/share/virtualenvs/cloudigrade-DXtd7Emz/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kholdawa/.local/share/virtualenvs/cloudigrade-DXtd7Emz/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/kholdawa/.local/share/virtualenvs/cloudigrade-DXtd7Emz/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/kholdawa/.local/share/virtualenvs/cloudigrade-DXtd7Emz/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/Users/kholdawa/dev/doppler/cloudigrade/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
RuntimeError: Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami
```

## Additional context
Effectively this is a feature of AWS to prevent a shared image from being re-distributed by a user of the image.  If we scan both account 1 and account 2, it is possible that we can successfully scan the AMI in account 1.  While account 2 scan will fail, we could correlate the scan from account 1.  Logic would have to change so the good scan is persisted.  Maybe it would help to know which account is the owner?

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 20, 2018, 10:08

This is related to https://gitlab.com/cloudigrade/cloudigrade/issues/458

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 20, 2018, 10:08

There might not be a solution for scanning here if AWS permissions lock us away from the AMI. We may need instead to have some kind of indicator or error to show users that we cannot access the AMI.

In this case, maybe we do what we've talked about regarding adding RHEL detection via tags! We could ask the customer to tag the shared image in their account much like we do for OCP.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 20, 2018, 10:09

We should also consider adding some kind of "error" terminal state for the image scanning process to put AMIs that fall into this case.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 20, 2018, 10:10

Would be good to get a timestamp of when the succeeded/errored/failed scan ran.

**Comment by katherine-black** [comment]
In GitLab by @abaiken on Aug 22, 2018, 15:29

Verified via running a scan on an instance created with from a private image with the box not checked. Instead of blowing up, it now looks like: 
```
[2018-08-22 19:26:43,178: INFO/ForkPoolWorker-3] Found a private image "ami-0c7a300ec227749f8" with inaccessible storage, marking as erred
``` 
and the image status is `error` :tada:
