### ISSUE TITLE
Task account.tasks.persist_inspection_cluster_results_task attempts to call 'items' on  list object

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#471]
In GitLab by @elijahd on Aug 23, 2018, 10:15

## Summary

Task account.tasks.persist_inspection_cluster_results_task bails with an exception because of calling a method that does not exist for `list` type objects.

## Steps to Reproduce

1. It appears this would probably happen with any inspection

## Expected Result

- No attempt to call non-existent methods

## Actual Result

```
[2018-08-23 13:39:19,001: ERROR/ForkPoolWorker-1] Task account.tasks.persist_inspection_cluster_results_task[2f7ed9a7-7d5e-4f2d-b0fa-caee7e2fb83b] raised unexpected: AttributeError("'list' object has no attribute 'items'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 547, in persist_inspection_cluster_results_task
    persist_aws_inspection_cluster_results(inspection_result)
  File "/opt/cloudigrade/account/tasks.py", line 513, in persist_aws_inspection_cluster_results
    for image_id, image_json in results.items():
AttributeError: 'list' object has no attribute 'items'
```

See attached logs....note there are other problems in there
[integrade-review-85-test-ex-xu4njncloudigrade-celery-worked42qt__2_.log](/uploads/1efe2e8c5b06c4bc8a67d24053de3ddc/integrade-review-85-test-ex-xu4njncloudigrade-celery-worked42qt__2_.log)

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Aug 23, 2018, 17:01

I finally managed to get a solution for https://gitlab.com/cloudigrade/cloudigrade/issues/464 together. The solution is three part as there were couple of things in play here.

First, we were never actually using the newest builds of houndigrade, the configuration was never updated to point at the images built by :gitlab: , that is solved here: https://gitlab.com/cloudigrade/shiftigrade/merge_requests/62 .

To make it easier for cloudigrade to reference houndigrade images I've also improved how we tag those images here: https://gitlab.com/cloudigrade/houndigrade/merge_requests/66 .

Finally, I noticed that cloudigrade would just throw inspection results away if something was wrong, I've made it more resilient and implemented similar methods to what @brad did with his changes to the log analyzer. MR here: https://gitlab.com/cloudigrade/cloudigrade/merge_requests/479

**Comment by katherine-black** [comment]
In GitLab by @abaiken on Aug 24, 2018, 11:54

I am looking at verifying this issue & I left you a small question on your cloudigrade MR (479).

**Comment by katherine-black** [comment]
In GitLab by @abaiken on Aug 24, 2018, 13:54

Created a small MR to remove the default list [here](https://gitlab.com/cloudigrade/cloudigrade/merge_requests/480).

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 15:13

Verified

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 15:13

closed
