### ISSUE TITLE
Creation of folders in s3 bucket creates messages that log analyzer cannot process

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#472]
In GitLab by @elijahd on Aug 23, 2018, 10:34

## Summary

It appears that when a cloud trail is created, the creation of the folders leading up to the messages may be recorded their own object creation event. The log analyzer attempts to open this directory as a file and it appears to cause a json decode error.

## Steps to Reproduce

1. Create an empty folder in the s3 bucket of a running cloudigrade

## Expected Result

- Nothing happens, message is processed and discarded

## Actual Result

- Message process causes exception and message is put back on queue

```
2018-08-23 13:47:18,982: INFO/ForkPoolWorker-1] Starting new HTTPS connection (1): integrade-review-85-test-ex-xu4njn-cloudigrade-s3.s3.amazonaws.com
[2018-08-23 13:47:19,069: ERROR/ForkPoolWorker-1] Unexpected error in log processing: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/cloudigrade/analyzer/tasks.py", line 61, in analyze_log
    success = _process_cloudtrail_message(message)
  File "/opt/cloudigrade/analyzer/tasks.py", line 102, in _process_cloudtrail_message
    content = json.loads(raw_content)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2018-08-23 13:47:19,070: ERROR/ForkPoolWorker-1] Failed to process message id 2bf8612e-656d-4f85-9444-6f88d9fe777f; leaving on queue.
```

## Additional context

Here is the message from sqs:
```
{"Records":[{"eventVersion":"2.0","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2018-08-23T13:28:49.551Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"AWS:AIDAIA2OYNONXMP6PZ3PW"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Notifications","bucket":{"name":"integrade-review-85-test-ex-xu4njn-cloudigrade-s3","ownerIdentity":{"principalId":"AAPU9L8N5W65S"},"arn":"arn:aws:s3:::integrade-review-85-test-ex-xu4njn-cloudigrade-s3"},"object":{"key":"AWSLogs/439727791560/","size":0,"eTag":"d41d8cd98f00b204e9800998ecf8427e","sequencer":"005B7EB6917F6A5D10"}}}]}
```

Maybe we should just open files if they are files ending in `.json.gz`
Also, it shows that the file size is `"size": 0`, so that may help to identify folders

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 23, 2018, 11:05

Turns out this was a configuration issue for the review environments:

see https://gitlab.com/cloudigrade/shiftigrade/issues/25

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 23, 2018, 11:05

closed
