### ISSUE TITLE
Unhandled error when copying image

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#473]
In GitLab by @elijahd on Aug 23, 2018, 13:48

## Summary

There is an error (`RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami"`) thrown by boto relating to not having enough permissions to copy an image. What is confusing is that there is only one **running** instance that is **owned** by the account. 

There **are** other terminated and stopped instances that come up in `describe-instances`, which I have attached: [instances.json](/uploads/48fe185d4b78dc45b35b2435a538ddd3/instances.json)

I have attached json from `aws --profile dev07 ec2 describe-images --filter=Name=is-public,Values=false > private-and-owned-images.json` : [private-and-owned-images.json](/uploads/2b7879505e1e5d821288ba7c62a051dc/private-and-owned-images.json) for reference.

## Steps to Reproduce

1. ???? Working on it

## Expected Result

- If it is a community or marketplace AMI causing this, we need to handle the error.

If it is a owned or private shared AMI for which we should have the right to copy the image, then something even stranger is afoot.

## Actual Result

```
[2018-08-23 16:04:12,123: ERROR/ForkPoolWorker-1] Task account.tasks.copy_ami_to_customer_account[fc50f29a-17d1-4e07-a52f-05b805316b10] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami",)
Traceback (most recent call last):
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 184, in copy_ami_to_customer_account
    raise e
  File "/opt/cloudigrade/account/tasks.py", line 152, in copy_ami_to_customer_account
    new_ami_id = aws.copy_ami(session, reference_ami.id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 183, in copy_ami
    SourceRegion=source_region,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
RuntimeError: Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami
```

## Additional context
The images that are listed from the api are as follows:

```
{'count': 3,
 'next': None,
 'previous': None,
 'results': [{'created_at': '2018-08-23T16:04:07.795568Z',
              'ec2_ami_id': 'ami-0a0c971e6f4a04a60',
              'id': 1,
              'is_encrypted': False,
              'openshift': True,
              'openshift_challenged': False,
              'openshift_detected': True,
              'owner_aws_account_id': '439727791560',
              'resourcetype': 'AwsMachineImage',
              'rhel': False,
              'rhel_challenged': False,
              'rhel_detected': False,
              'rhel_enabled_repos_found': False,
              'rhel_product_certs_found': False,
              'rhel_release_files_found': False,
              'rhel_signed_packages_found': False,
              'status': 'inspecting',
              'updated_at': '2018-08-23T16:09:57.248256Z'},
             {'created_at': '2018-08-23T16:04:07.798377Z',
              'ec2_ami_id': 'ami-01b965a6ad60e480e',
              'id': 2,
              'is_encrypted': False,
              'openshift': False,
              'openshift_challenged': False,
              'openshift_detected': False,
              'owner_aws_account_id': '343074669674',
              'resourcetype': 'AwsMachineImage',
              'rhel': False,
              'rhel_challenged': False,
              'rhel_detected': False,
              'rhel_enabled_repos_found': False,
              'rhel_product_certs_found': False,
              'rhel_release_files_found': False,
              'rhel_signed_packages_found': False,
              'status': 'preparing',
              'updated_at': '2018-08-23T16:04:08.239046Z'},
             {'created_at': '2018-08-23T16:35:20.811276Z',
              'ec2_ami_id': 'ami-0bf18d6709ff12ee8',
              'id': 3,
              'is_encrypted': False,
              'openshift': False,
              'openshift_challenged': False,
              'openshift_detected': False,
              'owner_aws_account_id': '439727791560',
              'resourcetype': 'AwsMachineImage',
              'rhel': False,
              'rhel_challenged': False,
              'rhel_detected': False,
              'rhel_enabled_repos_found': False,
              'rhel_product_certs_found': False,
              'rhel_release_files_found': False,
              'rhel_signed_packages_found': False,
              'status': 'preparing',
              'updated_at': '2018-08-23T16:35:20.826075Z'}]}
```

The customer account owns: 'ami-0a0c971e6f4a04a60' and 'ami-0bf18d6709ff12ee8'

Strangely enough, I cannot find any evidence of: 'ami-01b965a6ad60e480e' in either `describe-instances` or `describe-images`:
```
aws --profile dev07 ec2 describe-images --image-id=ami-01b965a6ad60e480e

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-01b965a6ad60e480e]' does not exist
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 23, 2018, 14:42

Continuing to try and figure out what the reproducer for this situation was, and registered the same account with no running instances.

To my suprise, I get see an instance and and image that are not present in my account:

Image:
```
pprint.pprint(client.get(urls.IMAGE, auth=auth))
{'count': 1,
 'next': None,
 'previous': None,
 'results': [{'created_at': '2018-08-23T16:04:07.798377Z',
              'ec2_ami_id': 'ami-01b965a6ad60e480e',
              'id': 2,
              'is_encrypted': False,
              'openshift': False,
              'openshift_challenged': False,
              'openshift_detected': False,
              'owner_aws_account_id': '343074669674',
              'resourcetype': 'AwsMachineImage',
              'rhel': False,
              'rhel_challenged': False,
              'rhel_detected': False,
              'rhel_enabled_repos_found': False,
              'rhel_product_certs_found': False,
              'rhel_release_files_found': False,
              'rhel_signed_packages_found': False,
              'status': 'preparing',
              'updated_at': '2018-08-23T16:04:08.239046Z'}]}
```
but when I query aws about this (within 5 minutes of this)

```
 aws --profile dev07 ec2 describe-images --image-id=ami-01b965a6ad60e480e

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-01b965a6ad60e480e]' does not exist
```

Instance:
```
pprint.pprint(client.get(urls.INSTANCE, auth=auth))
{'count': 1,
 'next': None,
 'previous': None,
 'results': [{'account': 'http://integrade-review-85-test-ex-xu4njn.review.gitlab.cloudigra.de/api/v1/account/3/',
              'created_at': '2018-08-23T18:32:22.840253Z',
              'ec2_instance_id': 'i-0364bd8b6daa5e38a',
              'id': 10,
              'region': 'us-east-2',
              'resourcetype': 'AwsInstance',
              'updated_at': '2018-08-23T18:32:22.840275Z',
              'url': 'http://integrade-review-85-test-ex-xu4njn.review.gitlab.cloudigra.de/api/v1/instance/10/'}]}
```
But again, when I query aws about this:
```
aws --profile dev07 ec2 describe-instances --instance-id i-0364bd8b6daa5e38a

An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-0364bd8b6daa5e38a' does not exist
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 14:43

Turns out there was an instance in a `us-east-2` and I was not finding the instance from the CLI because it was configured to use `us-east-1` by default

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 14:50

Using the correct region, got this info about the instance:

```
aws ec2 describe-images --profile dev07 --image-id ami-01b965a6ad60e480e --region us-east-2
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2018-08-03T16:26:41.000Z",
            "ImageId": "ami-01b965a6ad60e480e",
            "ImageLocation": "343074669674/MU-DEV-2018080312-FH-CENTOS7",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "343074669674",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-0b5a9376663478ba1",
                        "VolumeSize": 8,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdn",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-06dee248fe98b917e",
                        "VolumeSize": 2,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdo",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-0d725ddada89a3ca0",
                        "VolumeSize": 7,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdp",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-09b93ac639cdb19e2",
                        "VolumeSize": 7,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdq",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-07a8ee3311f9f32d7",
                        "VolumeSize": 2,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/sdr",
                    "VirtualName": "ephemeral0"
                },
                {
                    "DeviceName": "/dev/sds",
                    "VirtualName": "ephemeral1"
                },
                {
                    "DeviceName": "/dev/sdt",
                    "VirtualName": "ephemeral2"
                },
                {
                    "DeviceName": "/dev/sdu",
                    "VirtualName": "ephemeral3"
                }
            ],
            "Description": "Image automatically generated by Mu from MU-DEV-2018080312-FH-CENTOS7",
            "Hypervisor": "xen",
            "Name": "MU-DEV-2018080312-FH-CENTOS7",
            "RootDeviceName": "/dev/sda1",
            "RootDeviceType": "ebs",
            "VirtualizationType": "hvm"
        }
    ]
}
```

Then @katherine-black found more information about the original ami:

```
$ aws ec2 describe-images --image-ids ami-85908dfa
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2018-08-03T16:24:39.000Z",
            "ImageId": "ami-85908dfa",
            "ImageLocation": "343074669674/MU-DEV-2018080312-FH-CENTOS7",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "343074669674",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-099d06231ef3ecbb8",
                        "VolumeSize": 8,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdn",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-013a471752d87946d",
                        "VolumeSize": 2,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdo",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-0cc7d764b88205b87",
                        "VolumeSize": 7,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdp",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-06eb0ec4e9de81a9d",
                        "VolumeSize": 7,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/xvdq",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-082091c5d19a4d602",
                        "VolumeSize": 2,
                        "VolumeType": "gp2"
                    }
                },
                {
                    "DeviceName": "/dev/sdr",
                    "VirtualName": "ephemeral0"
                },
                {
                    "DeviceName": "/dev/sds",
                    "VirtualName": "ephemeral1"
                },
                {
                    "DeviceName": "/dev/sdt",
                    "VirtualName": "ephemeral2"
                },
                {
                    "DeviceName": "/dev/sdu",
                    "VirtualName": "ephemeral3"
                }
            ],
            "Description": "Image automatically generated by Mu from MU-DEV-2018080312-FH-CENTOS7",
            "Hypervisor": "xen",
            "Name": "MU-DEV-2018080312-FH-CENTOS7",
            "RootDeviceName": "/dev/sda1",
            "RootDeviceType": "ebs",
            "VirtualizationType": "hvm"
        }
    ]
}
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 15:51

Verified!

```
             {'created_at': '2018-08-24T19:47:26.713745Z',
              'ec2_ami_id': 'ami-01b965a6ad60e480e',
              'id': 2,
              'is_encrypted': False,
              'openshift': False,
              'openshift_challenged': False,
              'openshift_detected': False,
              'owner_aws_account_id': '343074669674',
              'resourcetype': 'AwsMachineImage',
              'rhel': False,
              'rhel_challenged': False,
              'rhel_detected': False,
              'rhel_enabled_repos_found': False,
              'rhel_product_certs_found': False,
              'rhel_release_files_found': False,
              'rhel_signed_packages_found': False,
              'status': 'inspected',
              'updated_at': '2018-08-24T19:47:31.146795Z'}]}
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 15:51

closed

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 24, 2018, 15:54

`[2018-08-24 19:47:31,134: INFO/ForkPoolWorker-1] Found a marketplace/community image "ami-01b965a6ad60e480e", marking as inspected`
