### ISSUE TITLE
Logs have lots of exceptions making it hard to read on test/stage when accounts are cleared out

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#476]
In GitLab by @elijahd on Aug 24, 2018, 10:23

## Summary

When we cleaned out the accounts on test, the cloud trails stayed set up in the "customer" accounts so they keep sending data. This data arriving for no longer existent AwsAccounts makes cloudigrade freak out a little bit.

## Steps to Reproduce

1. Register an account
1. Drop the accounts in the database
1. Don't go delete the customer cloud trail

## Expected Result

- something reasonable happens

## Actual Result

- Logs have lots of exceptions in them making it harder to notice real problems on test
```
[2018-08-24 14:12:27,293: ERROR/ForkPoolWorker-1] Unexpected error in log processing: AwsAccount matching query does not exist.
Traceback (most recent call last):
  File "/opt/cloudigrade/analyzer/tasks.py", line 61, in analyze_log
    success = _process_cloudtrail_message(message)
  File "/opt/cloudigrade/analyzer/tasks.py", line 118, in _process_cloudtrail_message
    instance_events, ami_tag_events
  File "/opt/cloudigrade/analyzer/tasks.py", line 170, in _get_aws_data_for_trail_events
    account = AwsAccount.objects.get(aws_account_id=account_id)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
account.models.AwsAccount.DoesNotExist: AwsAccount matching query does not exist.
```

## Additional context

This may be something we can fix with https://gitlab.com/cloudigrade/cloudigrade/issues/437

If users ever get access to the delete/archive feature, they may be dismayed to find out that their data is still coming to us. Maybe there is some setting we can do on amazon to stop the data flow.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Sep 19, 2018, 12:56

The exceptions here were real errors that we should not ignore, and in this case we resolved the underlying problem by clobbering some of our test accounts.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Sep 19, 2018, 12:56

closed
