### ISSUE TITLE
Machineimage expected to be present

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#477]
In GitLab by @katherine-black on Aug 24, 2018, 13:03

```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/cloudigrade/account/views.py", line 155, in list
    result = serializer.generate()
  File "/opt/cloudigrade/account/serializers.py", line 357, in generate
    name_pattern, account_id)
  File "/opt/cloudigrade/account/reports.py", line 320, in get_account_overviews
    for account in accounts
  File "/opt/cloudigrade/account/reports.py", line 320, in <listcomp>
    for account in accounts
  File "/opt/cloudigrade/account/reports.py", line 364, in get_account_overview
    images.append(event.machineimage.id)
AttributeError: 'NoneType' object has no attribute 'id'
```
```
class InstanceEvent(BasePolymorphicModel):
    machineimage = models.ForeignKey(
        MachineImage,
        on_delete=models.CASCADE,
        db_index=True,
        null=True,
    )
```
>should be a check to see if an event is associated with a machine image first before trying to grab the id

>since that model can be null

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Aug 27, 2018, 12:46

Logged in with the account that had this issue, the report endpoint now works.
```
$ http get https://test.cloudigra.de/api/v1/report/accounts/ "${AUTH}" start=="2018-06-01T00:00:00" end=="2018-08-30T00:00"
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Cache-control: private
Content-Length: 295
Content-Type: application/json
Date: Mon, 27 Aug 2018 16:43:38 GMT
Server: nginx/1.12.1
Set-Cookie: 0363cac70e8248650afc0b0855f64be8=3bd1bf601fd62a0b5c45e63a5c7e5563; path=/; HttpOnly; Secure
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "cloud_account_overviews": [
        {
            "arn": "arn:aws:iam::439727791560:role/CloudigradeRoleForTestEnv",
            "cloud_account_id": "439727791560",
            "creation_date": "2018-08-24T16:01:58.919961Z",
            "id": 11,
            "images": 10,
            "instances": 52,
            "name": "dev07",
            "openshift_instances": 4,
            "rhel_instances": 10,
            "type": "aws",
            "user_id": 4
        }
    ]
}
```

Here are some events with null `machineimage` references:
```
$ http get https://test.cloudigra.de/api/v1/event/ "${AUTH}" offset==2 limit==3
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Cache-control: private
Content-Length: 860
Content-Type: application/json
Date: Mon, 27 Aug 2018 16:45:29 GMT
Server: nginx/1.12.1
Set-Cookie: 0363cac70e8248650afc0b0855f64be8=3bd1bf601fd62a0b5c45e63a5c7e5563; path=/; HttpOnly; Secure
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "count": 132,
    "next": "https://test.cloudigra.de/api/v1/event/?limit=3&offset=5",
    "previous": "https://test.cloudigra.de/api/v1/event/?limit=3",
    "results": [
        {
            "event_type": "power_off",
            "id": 123,
            "instance": "https://test.cloudigra.de/api/v1/instance/77/",
            "instance_type": null,
            "machineimage": null,
            "occurred_at": "2018-08-24T06:29:14Z",
            "resourcetype": "AwsInstanceEvent",
            "subnet": null
        },
        {
            "event_type": "power_on",
            "id": 124,
            "instance": "https://test.cloudigra.de/api/v1/instance/77/",
            "instance_type": null,
            "machineimage": null,
            "occurred_at": "2018-08-24T06:28:32Z",
            "resourcetype": "AwsInstanceEvent",
            "subnet": null
        },
        {
            "event_type": "power_off",
            "id": 125,
            "instance": "https://test.cloudigra.de/api/v1/instance/78/",
            "instance_type": "m1.small",
            "machineimage": "https://test.cloudigra.de/api/v1/image/36/",
            "occurred_at": "2018-08-24T15:49:07Z",
            "resourcetype": "AwsInstanceEvent",
            "subnet": null
        }
    ]
}
```

Marking as verified :tada:

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Aug 27, 2018, 12:46

closed
