### ISSUE TITLE
Machineimage expected to be present 2, electric boogaloo

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#478]
In GitLab by @katherine-black on Aug 28, 2018, 10:59

Seems a lot like #471 just affects a different endpoint

```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/cloudigrade/account/views.py", line 187, in list
    result = serializer.generate()
  File "/opt/cloudigrade/account/serializers.py", line 406, in generate
    return reports.get_images_overviews(user_id, start, end, account_id)
  File "/opt/cloudigrade/account/reports.py", line 519, in get_images_overviews
    images = get_image_usages_for_account(start, end, account_id)
  File "/opt/cloudigrade/account/reports.py", line 490, in get_image_usages_for_account
    image_id = machineimage.id
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 28, 2018, 11:18

While looking at the logs trying to figure out what was going on I also noticed this traceback:

```
[2018-08-28 14:34:05,734: ERROR/ForkPoolWorker-1] Failed to save instances and/or events to the DB. Instance events: [CloudTrailInstanceEvent(occurred_at='2018-08-24T18:18:22Z', account_id='400313836798', region='us-east-2', instance_id='i-0bba083be8bb2d301', event_type='power_on')] AMI tag events: []
Traceback (most recent call last):
  File "/opt/cloudigrade/analyzer/tasks.py", line 126, in _process_cloudtrail_message
    described_images)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/cloudigrade/analyzer/tasks.py", line 425, in _save_results
    described_images)
  File "/opt/cloudigrade/analyzer/tasks.py", line 390, in _sanity_check_cloudtrail_findings
    ).format(instance_event))
util.exceptions.CloudTrailLogAnalysisMissingData: Missing image data for CloudTrailInstanceEvent(occurred_at='2018-08-24T18:18:22Z', account_id='400313836798', region='us-east-2', instance_id='i-0bba083be8bb2d301', event_type='power_on')
```

which makes me think that we are not saving some events that don't have image-id's associated with them

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Aug 28, 2018, 15:04

The changes I just pushed should resolve the issue as indicated in @katherine-black 's description. There's a chance it will also fix the underlying issue that led to @elijahd 's exception, but it's hard to know without more context and the info/error logs that would have preceded that specific error. Best I can say for now is to give it a try after this change and see if it behaves any better.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 30, 2018, 13:11

My accounts detail list is now displayed. Will continue to keep an eye out for any other problems, but I think I am going to verify this because the problem I had is resolved.

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Aug 30, 2018, 13:11

closed
