### ISSUE TITLE
failure to save instance if image not accessible at clount creation

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#525]
In GitLab by @infinitewarp on Dec 19, 2018, 16:40

## Summary

This is related to #518 but manifests in a different place. If you register a new cloud account (clount) that _at the time of registration_ has an instance running from an image that was shared but has since been revoked, cloudigrade fails to save any information about the clount's running instances.

## Steps to Reproduce

1. Create a new image in Account 1 with private access.
1. Add permissions for Account 2 to use that image.
1. Start an instance in Account 2 using the shared image.
1. Wait for the instance to complete startup.
1. Promptly remove Account 2's access from the image in Account 1.
1. Register Account 2 as a new cloud account in cloudigrade.
1. Wait for `account.tasks.initial_aws_describe_instances` to run in Celery.
1. Observe results.

## Expected Result

- An "unavailable" stub image is created.
- The running instance is created referencing that image.
- A power-on event is created referencing that instance.

## Actual Result

- The image, instance, and event are not saved.
- Relevant error seen in a Celery worker:
```
2018-12-19 21:14:00,909 | INFO | strategy.py:task_message_handler:156 | Received task: account.tasks.initial_aws_describe_instances[9be3c7d9-1836-4c65-b1c1-88d0cd0d4720]  
2018-12-19 21:14:09,148 | INFO | util.py:create_new_machine_images:135 | create_new_machine_images: all AMI IDs found: {'ami-06122adb0f6062a21'}
2018-12-19 21:14:09,159 | INFO | util.py:create_new_machine_images:143 | create_new_machine_images: Skipping known AMI IDs: set()
2018-12-19 21:14:09,252 | INFO | util.py:create_new_machine_images:161 | create_new_machine_images: Windows AMI IDs found: []
2018-12-19 21:14:09,287 | ERROR | trace.py:_log_error:256 | Task account.tasks.initial_aws_describe_instances[9be3c7d9-1836-4c65-b1c1-88d0cd0d4720] raised unexpected: DoesNotExist('AwsMachineImage matching query does not exist.',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 52, in initial_aws_describe_instances
    create_initial_aws_instance_events(account, instances_data)
  File "/opt/cloudigrade/account/util.py", line 41, in create_initial_aws_instance_events
    save_instance_events(account, instance_data, region)
  File "/opt/cloudigrade/account/util.py", line 72, in save_instance_events
    ec2_ami_id=instance_data['ImageId']
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
account.models.AwsMachineImage.DoesNotExist: AwsMachineImage matching query does not exist.
```

## Additional context

We probably want to make changes in `initial_aws_describe_instances` to save these "unavailable" images.

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Dec 20, 2018, 14:56

Instance in dev04:
![image](/uploads/0d2f01bd3e38dd4a21a4df4dad4b4af8/image.png)

Image in stage after deploying 0.1.11:
![image](/uploads/2f08414a0333fa0cec33203dbb32a287/image.png)

API Description of Image:
```
{
    "id": 39,
    "cloud_image_id": "ami-0c4b68112c118b313",
    "name": null,
    "status": "unavailable",
    "is_encrypted": false,
    "rhel": false,
    "rhel_detected": false,
    "rhel_challenged": false,
    "openshift": false,
    "openshift_detected": false,
    "openshift_challenged": false,
    "instances_seen": 1,
    "runtime_seconds": 124.560328
}
```

**Comment by katherine-black** [comment]
In GitLab by @werwty on Dec 21, 2018, 10:53

:+1: Verified. Images we don't have access to on clout creation gets the `unavailable` status and are not marked as rhel nor openshift.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Dec 21, 2018, 10:53

closed
