### ISSUE TITLE
WIP - Images hang in 'inspecting' status

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#534]
In GitLab by @mpierce on Feb 5, 2019, 21:09

## Summary

Images are created, volumes seem to get mounted, houndigrade is scaled down and images are not inspected.

## Steps to Reproduce

 This happens when running `test_discovery_and_inspection.py::test_find_running_instances` which:

        1) Create a user and authenticate with their password
        2) Create instances based off of a non-windows image
        3) Send a POST with the cloud account information to 'api/v1/account/'
        4) Send a GET to 'api/v1/instance/' and expect to get the instances we
            created
        5) Send a GET to 'api/v1/image/' and expect to get the image that
            the instances were based off of.
        6) Keep checking to see that the images progress from "pending",
            "preparing", "inspecting", to "inspected"

## Expected Result

        1) The server returns a 201 response with the information
            of the created account.
        2) We get 200 responses for our GET requests and information about
            the images includes inspection state information.
        3) The images are eventually inspected.

## Actual Result

        Time out, images are not inspected, status = 'inspecting'.

## Additional context

[Here](https://console.insights-dev.openshift.com/console/project/cloudigrade-qa/browse/pods/c-review-reinspect-pending-images-w-2-45w2t?tab=logs) is a link to the log showing an error related to the inspections, specifically:

`Task account.tasks.run_inspection_cluster[269f6658-7af9-4f10-aca8-aaa88ef75ac1] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidParameterValue) when calling the AttachVolume operation: Invalid value '/dev/xvdba' for unixDevice. Attachment point /dev/xvdba is already in use",)`

and fwiw, here is what seems to be the pertinent bits of the log:
[log.md](/uploads/214a127cf12a4bb4dab562dfe518fd7a/log.md)

And this is the current error displayed in the logs as of Monday afternoon (2/11):

`Task account.tasks.copy_ami_snapshot[4934b0e6-7384-4029-a14d-946103f49486] raised unexpected: DoesNotExist('AwsMachineImage matching query does not exist.',)`

More on this error message in the log:
[another_error.md](/uploads/2190276343fcd47976d91c8b91630e84/another_error.md)

Each time I run this, I get more/different errors. Here's the latest. 

`2019-02-12 18:47:14,764 | ERROR | tasks.py:analyze_log:92 | Unexpected error in log processing: Not a gzipped file (b'ba')` and 
`2019-02-12 18:47:14,766 | ERROR | tasks.py:analyze_log:102 | Failed to process message id 2aed32fa-129b-4319-8fa5-2a6fa7ca3a55; leaving on queue.` 
on and on. over and over. like 10 times.
[more_errors.md](/uploads/443be1bd72c06abe780a1d6fe5756e74/more_errors.md)

And later than the latest:
`2019-02-12 19:45:15,561 | ERROR | tasks.py:analyze_log:102 | Failed to process message id aecd111e-64d3-4518-b829-9767da1bb3ba; leaving on queue.
2019-02-12 19:45:15,762 | ERROR | tasks.py:analyze_log:92 | Unexpected error in log processing: Unterminated string starting at: line 1 column 1 (char 0)`
more details in here:
[yet_more_errors.md](/uploads/3e1925f02716d969a61f09d7e35d095b/yet_more_errors.md)

And here's one from this morning (2/13/2019):
```2019-02-13 14:16:40,378 | INFO | trace.py:info:124 | Task account.tasks.scale_up_inspection_cluster[7ec078aa-9d1d-4174-a923-1c8e64822b15] succeeded in 0.8695146618410945s: None
2019-02-13 14:16:41,036 | INFO | strategy.py:task_message_handler:156 | Received task: account.tasks.run_inspection_cluster[fc29fe5b-d0f3-40f8-89b6-7bca6747088c]  
2019-02-13 14:16:41,261 | ERROR | trace.py:_log_error:256 | Task account.tasks.run_inspection_cluster[fc29fe5b-d0f3-40f8-89b6-7bca6747088c] raised unexpected: DoesNotExist('AwsMachineImage matching query does not exist.',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 411, in run_inspection_cluster
    image = AwsMachineImage.objects.get(ec2_ami_id=message['ami_id'])
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
account.models.AwsMachineImage.DoesNotExist: AwsMachineImage matching query does not exist.
2019-02-13 14:17:29,240 | INFO | strategy.py:task_message_handler:156 | Received task: analyzer.tasks.analyze_log[eeb353de-4f76-4ebe-a74e-40c363c003e4]  
2019-02-13 14:17:39,307 | INFO | trace.py:info:124 | Task analyzer.tasks.analyze_log[eeb353de-4f76-4ebe-a74e-40c363c003e4] succeeded in 10.057150357402861s: ([], []) 
```

Date of error: 2/14/19

```2019-02-14 21:09:35,884 | INFO | trace.py:info:124 | Task account.tasks.copy_ami_snapshot[fa1a8f86-9e93-45e8-84e7-d9aaa24bcc1a] succeeded in 1.0235112980008125s: None
2019-02-14 21:09:38,852 | INFO | strategy.py:task_message_handler:156 | Received task: account.tasks.copy_ami_to_customer_account[419caaf4-54ce-4c87-82bc-384f380acac1]  
2019-02-14 21:09:40,585 | ERROR | trace.py:_log_error:256 | Task account.tasks.copy_ami_to_customer_account[419caaf4-54ce-4c87-82bc-384f380acac1] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.",)
Traceback (most recent call last):
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 217, in copy_ami_to_customer_account
    raise e
  File "/opt/cloudigrade/account/tasks.py", line 183, in copy_ami_to_customer_account
    new_ami_id = aws.copy_ami(session, reference_ami.id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 184, in copy_ami
    SourceRegion=source_region,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
RuntimeError: Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.
2019-02-14 21:09:52,935 | INFO | strategy.py:task_message_handler:156 | Received task: analyzer.tasks.analyze_log[5f6f0fad-b531-4a2c-8999-aa00f7a8493b]  
2019-02-14 21:10:03,026 | INFO | trace.py:info:124 | Task analyzer.tasks.analyze_log[5f6f0fad-b531-4a2c-8999-aa00f7a8493b] succeeded in 10.084922251291573s: ([], [])
```

Date of error 2/14/19 
```2019-02-14 21:33:54,274 | INFO | util.py:create_new_machine_images:226 | create_new_machine_images: Saving new AMI ID: ami-0d2e46db3ba19f204
2019-02-14 21:33:54,298 | ERROR | trace.py:_log_error:256 | Task account.tasks.initial_aws_describe_instances[f7b15b20-2f10-427d-abb8-8eafd79e1c1e] raised unexpected: IntegrityError('insert or update on table "account_instance" violates foreign key constraint "account_instance_account_id_5a5cd9af_fk_account_account_id"\nDETAIL:  Key (account_id)=(238) is not present in table "account_account".\n',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
psycopg2.IntegrityError: insert or update on table "account_instance" violates foreign key constraint "account_instance_account_id_5a5cd9af_fk_account_account_id"
DETAIL:  Key (account_id)=(238) is not present in table "account_account".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 54, in initial_aws_describe_instances
    create_initial_aws_instance_events(account, instances_data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "account_instance" violates foreign key constraint "account_instance_account_id_5a5cd9af_fk_account_account_id"
DETAIL:  Key (account_id)=(238) is not present in table "account_account".

2019-02-14 21:34:02,762 | INFO | strategy.py:task_message_handler:156 | Received task: account.tasks.initial_aws_describe_instances[f60332b4-b3f7-4605-bb3e-990ab973e3be]  
2019-02-14 21:34:04,409 | INFO | trace.py:info:124 | Task analyzer.tasks.analyze_log[3639ed04-3424-4161-ad33-0f0ac98abb06] succeeded in 10.108574161306024s: ([], [])
```

Date of error 2/14/19
```2019-02-14 21:56:06,035 | INFO | trace.py:info:124 | Task analyzer.tasks.analyze_log[eacee84e-c989-4299-946a-d1801b8d13ec] succeeded in 10.405797199346125s: ([sqs.Message(queue_url='https://sqs.us-east-1.amazonaws.com//527-case-insensitive-cloudigrade-cloudtrail-sqs' , receipt_handle='AQEBauML8SlX5QVAcXTKDejP/GwJpdeijTk5KuChwKB8HXiPrUYPb5r1d8wvwaoi7y/Lbg+qJdKQgAKXZggl88vp4pm+fSjllU8ExlMrwQreXcFEl51Hr8/6rsGM/E/JVj4K0nZF/QyoCs6j+6Rayx+O2lsXwJ1bc70U73dthEYEvVViIxxSWFLAuBaHIJpJV+AeHOqGhQAeir4v0mr64W8AtcY4gzjlkShpjLU1LAZ6fbsJ9ov6aO89G93qgj9tZrDMg9p6nh+VemiWb38/zXpiA+i2KbySOiNf3k5rVeKQOMW7Z+wPvPb5YRgo1921BquSPZKFy7kzn0OKWJUT13Nd3KfTT7yGTXo3Lz1En8SFZDTrAnGqpIG3JsXrniwBnZfzJkaiY6eXmSx5SoxPaUYIkrEET0AGcDy25uiRp/2j+xZrm+Mxgb3UxToZReZeK3Wk')], [])
2019-02-14 21:56:16,755 | ERROR | hub.py:fire_timers:146 | Error in timer: Exception("Request HTTP Error  HTTP 503  Service Unavailable (b'<ServiceUnavailableException/>')",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 136, in fire_timers
    entry()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 127, in _reschedules
    return fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 108, in _timeout_check
    self._process_pending_requests()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 130, in _process_pending_requests
    self._process(curl)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/promises.py", line 170, in __call__
    svpending(*ca, **ck)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/promises.py", line 163, in __call__
    return self.throw()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/promises.py", line 160, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/promises.py", line 163, in __call__
    return self.throw()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/promises.py", line 160, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/asynchronous/aws/connection.py", line 233, in _on_list_ready
    raise self._for_status(response, response.read())
Exception: Request HTTP Error  HTTP 503  Service Unavailable (b'<ServiceUnavailableException/>')
2019-02-14 21:56:54,211 | INFO | strategy.py:task_message_handler:156 | Received task: account.tasks.scale_up_inspection_cluster[c77081dc-bece-4e88-b1a4-616f392bf360]  
2019-02-14 21:56:54,415 | INFO | tasks.py:scale_up_inspection_cluster:370 | Auto Scaling group "527-case-insensitive-houndigrade-asg" is not scaled down. MinSize=1 MaxSize=1 DesiredCapacity=1 len(Instances)=1
```

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Feb 8, 2019, 13:13

@mpierce in the future you should grab those logs from the openshift containers because they get destroyed eventually

**Comment by katherine-black** [comment]
In GitLab by @elijahd on Feb 8, 2019, 13:13

oh wait, let me hold my horses I do see you have that markdown attached. my bad

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Feb 13, 2019, 10:25

If you get a chance, please pull down the messages that are causing these errors and attach them to this issue. It'll help us figure out what could be going wrong.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jul 23, 2019, 13:51

Closing this issue since it hasn't been revisited in a long time.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jul 23, 2019, 13:51

closed
