### ISSUE TITLE
Handle `None` image in `copy_ami_snapshot`

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#543]
In GitLab by @infinitewarp on Mar 7, 2019, 16:01

## Summary

We do not know exactly how this happens, but we have seen the following exception during inspection via integrade:

```
2019-03-07 20:11:47,447 | ERROR | trace.py:_log_error:256 | Task account.tasks.copy_ami_snapshot[d495fb97-9ad6-402c-84e0-f74df62e73bc] raised unexpected: AttributeError("'NoneType' object has no attribute 'get'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 93, in copy_ami_snapshot
    ami = aws.get_ami(session, ami_id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 146, in get_ami
    check_image_state(image)
  File "/opt/cloudigrade/util/aws/ec2.py", line 152, in check_image_state
    if image.state == 'available':
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```
It appears that in `copy_ami_snapshot` when we call `get_ami`, it is possible for AWS to return `None` instead of a proper image. When that happens, the latter call to `check_image_state` raises an unhandled `AttributeError`. That exception causes the task to fail in a way that **does not** retry, and the entire inspection process is aborted for the original image.

## Steps to Reproduce

1. Unknown. :frowning2: 

## Expected Result

- A meaningful message is logged at the ERROR level.
- The image status is set to "error" and saved.
- Inspection never completes.

## Actual Result

- Stack trace (above) is dumped.
- Image status remains in "inspecting".
- Inspection never completes.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 8, 2019, 10:12

FWIW, when we discovered and discussed this issue before entering this bug, we agreed that thorough unit testing here would be sufficient to verify since we don't know how to _actually_ reproduce it.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Mar 11, 2019, 15:17

I suspect what caused this error is (another instance of) integrade cleaning up by deregistering AMIs before the `copy_ami_snapshot` task completes. 

Since the AMI is valid, `session.resource('ec2', region_name=source_region).Image(image_id)` returns an image. But since the AMI is deregistered, checking image state results in this error.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 18, 2019, 10:15

Looks good to me. Thanks!

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 18, 2019, 10:15

closed
