### ISSUE TITLE
possible race condition at `initial_aws_describe_instances`

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#545]
In GitLab by @infinitewarp on Mar 14, 2019, 09:32

## Summary

I created a new review environment, and the first time I created an account, I saw the `initial_aws_describe_instances` task fail like this:

```
2019-03-14 13:23:04,900 | INFO | strategy.py:task_message_handler:156 | Received task: account.tasks.initial_aws_describe_instances[aa4db460-8eac-4cb5-b79a-3ea4b9b4132a]  
2019-03-14 13:23:04,955 | ERROR | trace.py:_log_error:256 | Task account.tasks.initial_aws_describe_instances[aa4db460-8eac-4cb5-b79a-3ea4b9b4132a] raised unexpected: DoesNotExist('AwsAccount matching query does not exist.',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 57, in initial_aws_describe_instances
    account = AwsAccount.objects.get(pk=account_id)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
account.models.AwsAccount.DoesNotExist: AwsAccount matching query does not exist.
```

We save the account immediately before firing this task. Is the calling method in a transaction? Is it possible the account hasn't saved by the time this happens?

## Steps to Reproduce

1. Set up a new review environment.
1. Create an account through the UI.
1. Hope that the timing works out like this.

## Expected Result

- AwsAccount is found when the `initial_aws_describe_instances` task runs, and the task completes successfully.

## Actual Result

- AwsAccount is not found when the `initial_aws_describe_instances` task runs. The task fails and does not attempt retry.

## Additional context

The second time I tried this, it worked. This is why I'm thinking there may be some kind of timing problem or race condition.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Mar 19, 2019, 10:20

This is the result of a known race condition since we have `'ATOMIC_REQUESTS': env('DJANGO_ATOMIC_REQUESTS', default=True)` set. Here is the workaround as recommended by celery:
http://docs.celeryproject.org/en/latest/userguide/tasks.html#database-transactions

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 22, 2019, 09:39

Looks good to me. Thanks!

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 22, 2019, 09:39

closed
