### ISSUE TITLE
Marketplace-based AMIs fail to attach volumes

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#551]
In GitLab by @infinitewarp on Mar 22, 2019, 11:15

## Summary

In a test.cloudigra.de Celery worker, I just saw an unhandled exception with this error message:

> An error occurred (OptInRequired) when calling the AttachVolume operation: In order to use this AWS Marketplace product you need to accept terms and subscribe.

It looks like SOMETIMES we may manage to get far enough with a Marketplace-based AMI that we have a copy and a volume, but we can't attach that volume to the ECS inspection cluster. Our previous experience indicated that this would fail earlier in the process (where we handle it). We need to handle this here and update our image's status to "inspected" so it doesn't attempt retry later.

## Steps to Reproduce

1. TBD ¯\\\_(ツ)\_/¯

## Expected Result

- Marketplace-based AMIs do not cause the inspection process to fail. They are given an "inspected" status so inspection will not automatically retry and the `aws_marketplace_image` value is set `True`.

## Actual Result

```
2019-03-22 14:15:24,694 | INFO | tasks.py:run_inspection_cluster:476 | run_inspection_cluster attaching volume vol-0c2ae03dfe2a9ae93 from AMI ami-04fb19cd19041c645 to instance i-0d517694587491f2a at /dev/xvdbc
2019-03-22 14:15:24,891 | ERROR | trace.py:_log_error:256 | Task account.tasks.run_inspection_cluster[a184e71a-8515-4e7f-86f4-59c8b027434d] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (OptInRequired) when calling the AttachVolume operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce ",)
Traceback (most recent call last):
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 481, in run_inspection_cluster
    Device=mount_point, InstanceId=ec2_instance_id)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (OptInRequired) when calling the AttachVolume operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
RuntimeError: Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (OptInRequired) when calling the AttachVolume operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce
```

## Additional context

???

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 22, 2019, 11:20

Attached are the logs from the three worker pods that I had downloaded when I first spotted this issue. You can find this specific exception in `c-w-55-bwtbc.log`.

[c-w-55-bwtbc.log](/uploads/1c75aae3b0d2ba72c25b14292e84b9cd/c-w-55-bwtbc.log)
[c-w-55-g8nxj.log](/uploads/f5d8503c20ff1f632d9216505a020370/c-w-55-g8nxj.log)
[c-w-55-hjgjk.log](/uploads/a19896f832d7341dd479761159e18c01/c-w-55-hjgjk.log)

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Mar 26, 2019, 12:23

Deployed to test and reinspected the bad image.

```
2019-03-26 16:17:00,728 | WARNING | tasks.py:run_inspection_cluster:486 | Found a marketplace AMI "ami-04fb19cd19041c645" when trying to copy volume, this should not happen, but here we are.
```

```
$ http get https://test.cloudigra.de/api/v1/image/100/ "${AUTH}"
HTTP/1.1 200 OK
Allow: GET, PUT, PATCH, HEAD, OPTIONS
Cache-control: private
Content-Length: 698
Content-Type: application/json
Date: Tue, 26 Mar 2019 16:17:21 GMT
Server: nginx/1.12.1
Set-Cookie: d709a0d58a3a7c5d34707f59ba38eff5=7692dd9126cb66694a2618601c7fa9e9; path=/; HttpOnly; Secure
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "created_at": "2019-03-11T19:03:23.393939Z",
    "ec2_ami_id": "ami-04fb19cd19041c645",
    "id": 100,
    "inspection_json": null,
    "is_cloud_access": false,
    "is_encrypted": false,
    "is_marketplace": false,
    "name": "supa-bad-image",
    "openshift": false,
    "openshift_challenged": false,
    "openshift_detected": false,
    "owner_aws_account_id": "528231032158",
    "platform": "none",
    "region": "us-east-1",
    "resourcetype": "AwsMachineImage",
    "rhel": false,
    "rhel_challenged": false,
    "rhel_detected": false,
    "rhel_enabled_repos_found": false,
    "rhel_product_certs_found": false,
    "rhel_release_files_found": false,
    "rhel_signed_packages_found": false,
    "status": "inspected",
    "updated_at": "2019-03-26T16:17:01.766286Z",
    "url": "https://test.cloudigra.de/api/v1/image/100/"
}
```
```
cloudigrade_test=> select * from account_awsmachineimage where ec2_ami_id='ami-04fb19cd19041c645';
-[ RECORD 1 ]---------+----------------------
machineimage_ptr_id   | 100
ec2_ami_id            | ami-04fb19cd19041c645
platform              | none
owner_aws_account_id  | 528231032158
region                | us-east-1
aws_marketplace_image | t
```

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 28, 2019, 10:29

Looks good to me. Thanks!

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Mar 28, 2019, 10:29

closed
