### ISSUE TITLE
Marketplace-based AMIs fail to attach volumes part 2, electric boogaloo

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#555]
In GitLab by @katherine-black on Mar 28, 2019, 14:49

## Summary

In a www.cloudigra.de Celery worker, I just saw an unhandled exception with this error message:

> Cannot attach volume 'vol-0b96f71c49b0aa71e' with Marketplace codes as the instance 'i-0287207b497222fb7' is not in the 'stopped' state.",)

It looks like SOMETIMES we may manage to get far enough with a Marketplace-based AMI that we have a copy and a volume, but we can't attach that volume to the ECS inspection cluster. Our previous experience indicated that this would fail earlier in the process (where we handle it). We need to handle this here and update our image's status to "inspected" so it doesn't attempt retry later.

## Steps to Reproduce

1. TBD ¯\\\_(ツ)\_/¯

## Expected Result

- Marketplace-based AMIs do not cause the inspection process to fail. They are given an "inspected" status so inspection will not automatically retry and the `aws_marketplace_image` value is set `True`.

## Actual Result

```
2019-03-28 18:36:13,564 | ERROR | trace.py:_log_error:256 | Task account.tasks.run_inspection_cluster[c2260c30-aa4d-40cf-ab22-121327c0202f] raised unexpected: RuntimeError("Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (IncorrectInstanceState) when calling the AttachVolume operation: Cannot attach volume 'vol-0b96f71c49b0aa71e' with Marketplace codes as the instance 'i-0287207b497222fb7' is not in the 'stopped' state.",)
Traceback (most recent call last):
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/account/tasks.py", line 493, in run_inspection_cluster
    raise e
  File "/opt/cloudigrade/account/tasks.py", line 481, in run_inspection_cluster
    Device=mount_point, InstanceId=ec2_instance_id)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the AttachVolume operation: Cannot attach volume 'vol-0b96f71c49b0aa71e' with Marketplace codes as the instance 'i-0287207b497222fb7' is not in the 'stopped' state.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 192, in wrapped
    raise RuntimeError(message)
RuntimeError: Unexpected AWS error <class 'botocore.exceptions.ClientError'>: An error occurred (IncorrectInstanceState) when calling the AttachVolume operation: Cannot attach volume 'vol-0b96f71c49b0aa71e' with Marketplace codes as the instance 'i-0287207b497222fb7' is not in the 'stopped' state.
```

## Additional context

???

**Comment by katherine-black** [comment]
In GitLab by @werwty on Apr 4, 2019, 13:15

LGTM. Checked image in prod and it's marked as inspected

```
{
    "created_at": "2018-09-24T23:45:20.072284Z",
    "ec2_ami_id": "ami-077b0e78",
    "id": 77,
    "inspection_json": null,
    "is_cloud_access": false,
    "is_encrypted": false,
    "is_marketplace": false,
    "name": "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180522-d83d0782-cb94-46d7-8993-f4ce15d1a484-ami-a4dc46db.4",
    "openshift": false,
    "openshift_challenged": false,
    "openshift_detected": false,
    "owner_aws_account_id": "",
    "platform": "none",
    "region": null,
    "resourcetype": "AwsMachineImage",
    "rhel": false,
    "rhel_challenged": false,
    "rhel_detected": false,
    "rhel_enabled_repos_found": false,
    "rhel_product_certs_found": false,
    "rhel_release_files_found": false,
    "rhel_signed_packages_found": false,
    "status": "inspected",
    "updated_at": "2019-04-03T21:46:30.710644Z",
    "url": "https://www.cloudigra.de/api/v1/image/77/"
}
```

**Comment by katherine-black** [comment]
In GitLab by @werwty on Apr 4, 2019, 13:15

closed
