### ISSUE TITLE
Update async tasks to use v2 models

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#563]
In GitLab by @infinitewarp on Apr 16, 2019, 14:24

## Summary

As an Insights platform Cloud Meter customer, I want my data to be inspected with v2 like it was with v1 so I can do interesting things with the results.

## Acceptance Criteria

- [x] Verify the async tasks around inspection, etc. work as expected following the v2 model changes.

## Assumptions and Questions

- We should have completed https://gitlab.com/cloudigrade/cloudigrade/issues/553 before starting so that we can confidently refactor the existing task functions.
- This connects the work started in https://gitlab.com/cloudigrade/cloudigrade/issues/555 with actually working tasks.
- QE will be "writing the tests from scratch" for this since v1 tests are not in great shape, but "we have a plan" to get started on them. QE devs may consult with former team QE members (Calvin? Elijah? Elyezer?) to refine that plan.

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 3, 2019, 16:36

marked the task **Verify the async tasks around inspection, etc. work as expected following the v2 model changes.** as completed

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 5, 2019, 09:23

Running the test results in a timeout after an hour with the state still at `preparing`.

Here are the errors I'm seeing in the [worker logs](https://console.insights-dev.openshift.com/console/project/cloudigrade-qa/browse/rc/c-review-557-v2-tasks-w-1?tab=logs): 
```2019-06-04 22:42:40,077 | ERROR | trace.py:_log_error:256 | requestid:83b59862-38d2-465d-a64b-5c22ae172a87 | Task api.tasks.remove_snapshot_ownership[e36db933-a020-4fcf-8f80-34cee39c064c] raised unexpected: AwsSnapshotError('Snapshot snap-02fff67f337ac7c87 has state error at 0%')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 359, in remove_snapshot_ownership
    aws.check_snapshot_state(snapshot_copy)
  File "/opt/cloudigrade/util/aws/ec2.py", line 440, in check_snapshot_state
    raise AwsSnapshotError(message)
util.exceptions.AwsSnapshotError: Snapshot snap-02fff67f337ac7c87 has state error at 0%
2019-06-04 22:42:44,057 | ERROR | trace.py:_log_error:256 | requestid:83b59862-38d2-465d-a64b-5c22ae172a87 | Task api.tasks.create_volume[39810b58-fd84-4a95-8d7f-fa26eb3a5fbe] raised unexpected: AwsSnapshotError('Snapshot snap-02fff67f337ac7c87 has state error at 0%')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 400, in create_volume
    volume_id = aws.create_volume(snapshot_copy_id, zone)
  File "/opt/cloudigrade/util/aws/ec2.py", line 425, in create_volume
    check_snapshot_state(snapshot)
  File "/opt/cloudigrade/util/aws/ec2.py", line 440, in check_snapshot_state
raise AwsSnapshotError(message)
util.exceptions.AwsSnapshotError: Snapshot snap-02fff67f337ac7c87 has state error at 0%

6/5/19 error:

2019-06-05 00:26:13,904 | INFO | strategy.py:task_message_handler:157 | requestid:None | Received task: api.tasks.run_inspection_cluster[535b7d52-68b2-417d-8a84-b9d3a5a074a1]  
2019-06-05 00:26:14,039 | ERROR | trace.py:_log_error:256 | requestid:7fd189f1-ec4e-4587-80d7-d2c5af1928ed | Task api.tasks.run_inspection_cluster[535b7d52-68b2-417d-8a84-b9d3a5a074a1] raised unexpected: DoesNotExist('AwsMachineImage matching query does not exist.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 189, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 542, in run_inspection_cluster
    image = AwsMachineImage.objects.get(ec2_ami_id=message['ami_id'])
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
api.models.AwsMachineImage.DoesNotExist: AwsMachineImage matching query does not exist.```

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 7, 2019, 16:31

closed
