### ISSUE TITLE
http delete cloud account return 500 error

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#601]
In GitLab by @infinitewarp on Jun 13, 2019, 15:15

## Summary

HTTP DELETEing a cloud account returns a 500 error.

## Steps to Reproduce

1. register a cloud account
1. http delete it like
  ```
  http --verify=no --auth rmoura@redhat.com:redhat \
      DELETE https://qa.cloud.paas.upshift.redhat.com/api/cloudigrade/v2/accounts/77/ \
      X-4Scale-Env:ci X-4Scale-Branch:557-v2-tasks
  ```

## Expected Result

- success!

## Actual Result

```
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
X-Powered-By: Express
allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
connection: keep-alive
content-type: application/json
date: Thu, 13 Jun 2019 19:08:55 GMT
server: openresty/1.13.6.1
set-cookie: a549c90418df47840900855e57bbdfae=c61d5cfbaa7eaef0299fe327fcbfae7e; path=/; HttpOnly; Secure
vary: Accept
x-cloudigrade-request-id: 68775721-3a1b-47d6-9a5a-683784322742
x-fakamai-app-hint: API
x-fakamai-downsteam-host: https://api-gateway-qa.5a9f.insights-dev.openshiftapps.com
x-fakamai-env: qa
x-frame-options: SAMEORIGIN
x-rh-insights-request-id: b8a08bf79c1541bd9ff0587b63ce6b8b

{
    "detail": "A server error occurred."
}
```

## Additional context

I found this in the server logs at the time of the request:
```
2019-06-13 19:08:55,972 | ERROR | exceptions.py:api_exception_handler:131 | requestid:68775721-3a1b-47d6-9a5a-683784322742 | 'NoneType' object has no attribute 'delete'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 93, in destroy
    self.perform_destroy(instance)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 97, in perform_destroy
    instance.delete()
  File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/cloudigrade/api/models.py", line 74, in delete
    instance.delete()
  File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/cloudigrade/api/models.py", line 430, in delete
    self.machine_image.delete()
AttributeError: 'NoneType' object has no attribute 'delete'
```

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 14, 2019, 10:38

closed
