### ISSUE TITLE
Exception raised during cloud account registration > instances not found

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#604]
In GitLab by @mpierce on Jun 19, 2019, 15:30

## Summary

I run instances in AWS, and look for them in Cloudigrade, but they intermittently aren't there (maybe `image`-dependent, maybe not?).

## Steps to Reproduce

1. Trigger an instance of an image to run in AWS
2. Create a new account in Cloudigrade
3. Poll Cloudigrade watching for the instance to appear in the account (`get` request to the `instances/` endpoint)

## Expected Result

- After a time (< 10 min) see that the instance is discovered by Cloudigrade and the `instance_id` is returned in the response of the above `get` request.

## Actual Result

- After a time (~ 15 min) the instance is not found though the instance is visible/running in AWS.

## Additional context

```Instance id: i-05acc8e4ebec1481e (listed as running in the AWS console)
Image_id: ami-065d0be9883aa064a (listed in the second line of the log as 'found')
 
Here is the log from the worker:
 
2019-06-19 16:10:16,384 | INFO | util.py:create_new_machine_images:318 | requestid:b5ec7001-4552-4728-a9a3-3389c86a1bd8 | create_new_machine_images: all AMI IDs found: {'ami-0d2e46db3ba19f204', 'ami-065d0be9883aa064a', 'ami-0b817f1f3a9927361'}
2019-06-19 16:10:16,390 | INFO | util.py:create_new_machine_images:326 | requestid:b5ec7001-4552-4728-a9a3-3389c86a1bd8 | create_new_machine_images: Skipping known AMI IDs: {'ami-0b817f1f3a9927361'}
2019-06-19 16:10:16,493 | INFO | util.py:create_new_machine_images:345 | requestid:b5ec7001-4552-4728-a9a3-3389c86a1bd8 | create_new_machine_images: Windows AMI IDs found: []
2019-06-19 16:10:16,493 | INFO | util.py:create_new_machine_images:362 | requestid:b5ec7001-4552-4728-a9a3-3389c86a1bd8 | create_new_machine_images: Saving new AMI ID: ami-065d0be9883aa064a
2019-06-19 16:10:16,498 | INFO | util.py:create_new_machine_images:362 | requestid:b5ec7001-4552-4728-a9a3-3389c86a1bd8 | create_new_machine_images: Saving new AMI ID: ami-0d2e46db3ba19f204
2019-06-19 16:10:16,507 | ERROR | trace.py:_log_error:256 | requestid:b5ec7001-4552-4728-a9a3-3389c86a1bd8 | Task api.tasks.initial_aws_describe_instances[305945d0-9995-4f08-b1ad-08ee1a0254d8] raised unexpected: DoesNotExist('MachineImage matching query does not exist.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 197, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 86, in initial_aws_describe_instances
    create_initial_aws_instance_events(account, instances_data)
  File "/opt/cloudigrade/api/util.py", line 437, in create_initial_aws_instance_events
    instance = save_instance(account, instance_data, region)
  File "/opt/cloudigrade/api/util.py", line 496, in save_instance
    machineimage = awsmachineimage.machine_image.get()
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
api.models.MachineImage.DoesNotExist: MachineImage matching query does not exist.
 ```

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jun 20, 2019, 10:34

After adding a workaround and recreating the review environment, we're still seeing this happen in the celery worker:

```
2019-06-20 14:29:05,174 | ERROR | trace.py:_log_error:256 | requestid:eb233f42-26fe-4248-8f4d-4ae0e972d205 | Task api.tasks.copy_ami_to_customer_account[163a5f97-27bf-4f6b-9a17-bb48a9f9a8ae] raised unexpected: DoesNotExist('AwsMachineImage matching query does not exist.')
Traceback (most recent call last):
  File "/opt/cloudigrade/api/tasks.py", line 290, in copy_ami_to_customer_account
    new_ami_id = aws.copy_ami(session, reference_ami.id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 240, in copy_ami
    SourceRegion=source_region,
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 197, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 333, in copy_ami_to_customer_account
    ami = AwsMachineImage.objects.get(ec2_ami_id=reference_ami_id)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
api.models.AwsMachineImage.DoesNotExist: AwsMachineImage matching query does not exist.
```

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jun 20, 2019, 10:38

also in `create_aws_machine_image_copy`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 197, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 245, in copy_ami_snapshot
    create_aws_machine_image_copy(ami_id, reference_ami_id)
  File "/opt/cloudigrade/api/util.py", line 903, in create_aws_machine_image_copy
    reference = AwsMachineImage.objects.get(ec2_ami_id=reference_ami_id)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
api.models.AwsMachineImage.DoesNotExist: AwsMachineImage matching query does not exist.
```

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jun 21, 2019, 14:11

Still seeing this exception from the celery worker after the latest push that ensures that `MachineImage`s are always (AFAICT) created with `AwsMachineImage` and `AwsMachineImageCopy`s...

```
2019-06-21 13:17:56,276 | ERROR | trace.py:_log_error:256 | requestid:7ad3639a-79c9-4436-a807-e9029aa3f985 | Task api.tasks.copy_ami_to_custome
r_account[716a8e4c-dc2f-4652-87d6-77012f265a7d] raised unexpected: DoesNotExist('AwsMachineImage matching query does not exist.')
Traceback (most recent call last):
  File "/opt/cloudigrade/api/tasks.py", line 302, in copy_ami_to_customer_account
    new_ami_id = aws.copy_ami(session, reference_ami.id, snapshot_region)
  File "/opt/cloudigrade/util/aws/ec2.py", line 240, in copy_ami
    SourceRegion=source_region,
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access
the storage of this ami

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 197, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 345, in copy_ami_to_customer_account
    ami = AwsMachineImage.objects.get(ec2_ami_id=reference_ami_id)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
api.models.AwsMachineImage.DoesNotExist: AwsMachineImage matching query does not exist.
```

It looks like there's a case in which the original AwsMachineImage simply isn't being created.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jun 24, 2019, 15:32

In the worker:
```
2019-06-24 16:24:12,735 | ERROR | trace.py:_log_error:256 | requestid:fa8205c0-2ddc-4d41-81c9-563ea3a0b34c | Task api.tasks.initial_aws_describe_instances[2a7b7917-6d57-4ab2-8fc6-a1fd3fa42c2a] raised unexpected: IntegrityError('insert or update on table "api_instance" violates foreign key constraint "api_instance_cloud_account_id_09bb4aa6_fk_api_cloudaccount_id"\nDETAIL:  Key (cloud_account_id)=(71) is not present in table "api_cloudaccount".\n')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "api_instance" violates foreign key constraint "api_instance_cloud_account_id_09bb4aa6_fk_api_cloudaccount_id"
DETAIL:  Key (cloud_account_id)=(71) is not present in table "api_cloudaccount".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/cloudigrade/util/aws/helper.py", line 197, in wrapped
    result = original_function(*args, **kwargs)
  File "/opt/cloudigrade/api/tasks.py", line 95, in initial_aws_describe_instances
    create_initial_aws_instance_events(account, instances_data)
  File "/usr/local/lib64/python3.7/site-packages/django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "api_instance" violates foreign key constraint "api_instance_cloud_account_id_09bb4aa6_fk_api_cloudaccount_id"
DETAIL:  Key (cloud_account_id)=(71) is not present in table "api_cloudaccount".

2019-06-24 16:24:13,146 | INFO | trace.py:info:124 | requestid:2b8d3860-fd19-4334-8b4a-c5b1ea84d0bc | Task api.tasks.enqueue_ready_volume[a0a7a08b-2881-4838-aaee-c1bb64ba6fb2] succeeded in 0.33421650202944875s: None
```

Meanwhile, in the API logs:
```
2019-06-24 16:24:06,141 | INFO | authentication.py:authenticate:40 | requestid:0c2d1de7-3fca-455b-8a09-6f9a502596d9 | Authenticating via insights, INSIGHTS_REQUEST_ID: 7f0d9dd3e8e04e689f577514be8a4348
2019-06-24 16:24:06,148 | INFO | models.py:delete:56 | requestid:0c2d1de7-3fca-455b-8a09-6f9a502596d9 | deleting CloudAccount-related content object: AwsCloudAccount object (71)
2019-06-24 16:24:06,637 | INFO | models.py:delete:112 | requestid:0c2d1de7-3fca-455b-8a09-6f9a502596d9 | attempting to disable cloudtrail "review-557-v2-tasks439727791560" via ARN "arn:aws:iam::439727791560:role/allow-dev11-cloudigrade-metering"
2019-06-24 16:24:06,749 | INFO | models.py:delete:60 | requestid:0c2d1de7-3fca-455b-8a09-6f9a502596d9 | deleting CloudAccount object (71)
```

So, it looks like the cloud account was deleted at the same time as when the worker was trying to run `initial_aws_describe_instances`. My guess is that it was actually during the time when the task was calling `describe_instances_everywhere` because before that we check that the account exists, and only *after* it do we start this transaction.

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jul 2, 2019, 10:26

closed
