### ISSUE TITLE
OpenAPI spec errors after concurrent API changes

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#711]
In GitLab by @mpierce on Jun 26, 2020, 09:33

## Summary

Updating `iqe-cloudmeter-plugin` API resulted in the following errors:

```
Errors: 
        -attribute paths.'/api/cloudigrade/v2/concurrent/'(get).responses.200.description is missing
        -attribute paths.'/api/cloudigrade/v2/concurrent/'(get).responses.description is not of type `object`
```

Seems to me that the first one, `description is missing`, seems nit-picky, but the second one looks similar to the issue that Bihan fixed recently - [#697](https://gitlab.com/cloudigrade/cloudigrade/-/issues/697)

## Steps to Reproduce

1. Run the script in `iqe-cloudmeter-plugin` to update the API. `env ENV_FOR_DYNACONF=qa iqe apigen update cloudmeter`

## Expected Result

- Successful update

## Actual Result

- See errors above. 
- `iqe-cloudmeter-plugin` API handler update failed

## Additional context

```
(.iqe_venv) ➜  iqe-cloudmeter-plugin git:(682-instance-count) ✗ env ENV_FOR_DYNACONF=qa iqe apigen update cloudmeter
/Users/maribethpierce/insights/iqe-tests/iqe/base/__init__.py:51: IQEMissplacedConfigurationSectionWarning: plugin cloudmeter has unexpected settings key default.VM in /Users/maribethpierce/insights/iqe-cloudmeter-plugin/iqe_cloudmeter/conf/settings.default.yaml
  f"plugin {ep.name} has unexpected settings key {env}.{key} in {path}", category=cls
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/base/ssh.py:22: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  DEFAULT_CONNECTION_TIMEOUT = iqe_conf.VM.ssh_connection_timeout
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/base/ssh.py:23: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  DEFAULT_CONNECTION_RETRIES = iqe_conf.VM.ssh_connection_retries
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/base/ssh.py:24: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  DEFAULT_CONNECTION_RETRIES_DELAY = iqe_conf.VM.ssh_connection_retries_delay
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/base/ssh.py:25: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  DEFAULT_COMMAND_TIMEOUT = iqe_conf.VM.ssh_command_timeout
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/base/ssh.py:26: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  SSH_CONNECT_VIA_IP_ADDRESS = iqe_conf.VM.ssh_connect_via_ip_address
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/base/ssh.py:27: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  SSH_AWAIS_USE_NEW_CONNECTION = iqe_conf.VM.ssh_always_use_new_connection
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_vm/__init__.py:21: IQEDeprecationWarning: DEPRECATED: global conf usage is deprecated iqe_integration_tests 0.33.0 will remove support for this functionality. A possible replacement is: Config must be accessed via application or plugin passthrough.
  conf = iqe_conf.VM
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_platform_ui/__init__.py:179: IQEDeprecationWarning: DEPRECATED: 'Settings' tests and pages will be removed; iqe_platform_ui_plugin 0.14.30 will remove support for this functionality. A possible replacement is: 'Settings' tests, pages, and destinations have been moved to the iqe-settings-plugin.
  class Settings(IQENavigateStep):
/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_platform_ui/__init__.py:220: IQEDeprecationWarning: DEPRECATED: 'User preferences' tests and pages will be removed; iqe_platform_ui_plugin 0.14.30 will remove support for this functionality. A possible replacement is: 'User preferences' tests, pages, and destinations have been moved to the iqe-settings-plugin.
  class UserPreferences(IQENavigateStep):
INFO:root:Using <function client_obj_maker.<locals>.make_obj at 0x10a14f680> object....with url https://qa.cloud.redhat.com and verify_ssl set to False
INFO:root:Setting auth_type to jwt
no service name
downloading https://qa.cloud.redhat.com/api/cloudigrade/v2/openapi.json
⚠️ WARNING: enforcing OPENAPI_GENERATOR_VERSION=4.3.1
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors: 
        -attribute paths.'/api/cloudigrade/v2/concurrent/'(get).responses.200.description is missing
        -attribute paths.'/api/cloudigrade/v2/concurrent/'(get).responses.description is not of type `object`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:480)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Traceback (most recent call last):
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/bin/iqe", line 11, in <module>
    load_entry_point('iqe-integration-tests', 'console_scripts', 'iqe')()
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_goatee/command.py", line 386, in update
    stock_templates=stock_templates,
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_goatee/command.py", line 312, in generate_api
    **config_options,
  File "/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_goatee/command.py", line 83, in run_openapi_generator
    env=my_env,
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_goatee/data/openapi-generator-cli.sh', 'generate', '-i', '/Users/maribethpierce/insights/iqe-cloudmeter-plugin/iqe_cloudmeter/data/api.cloudmeter.spec.json', '-g', 'python', '-o', '/Users/maribethpierce/insights/iqe-cloudmeter-plugin', '-t', '/Users/maribethpierce/insights/iqe-tests/.iqe_venv/lib/python3.7/site-packages/iqe_goatee/data/python', '--package-name', 'iqe_cloudmeter_api', '-p', 'generateSourceCodeOnly=True', '-p', 'enablePostProcessFile=False', '-p', 'excludeTests=True', '-p', 'generateApiDocs=False', '-p', 'generateApiTests=False', '-p', 'generateModelDocs=False', '-p', 'generateModelTests=False', '-p', 'iqeSanitizeObj=filter_readonly']' returned non-zero exit status 1.```

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 26, 2020, 16:46

:thumbsup_tone2:

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 26, 2020, 16:46

closed

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 26, 2020, 17:55

reopened

**Comment by katherine-black** [comment]
In GitLab by @mpierce on Jun 26, 2020, 17:55

closed
