### ISSUE TITLE
Running `seed_review_data` twice produces errors

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#717]
In GitLab by @infinitewarp on Jul 15, 2020, 13:02

## Summary

As seen when review environments redeploy, our GitLab pipeline always runs `seed_review_data`, but after the first time, it always fails with errors. We ignore those errors and allow the pipeline to proceed, but we could do better.

## Steps to Reproduce

1. Create a branch in gitlab and observe the pipeline that sets up the review environment.
1. After all related jobs have completed, run the "Deploy Review" job a second time.

## Expected Result

- No errors

## Actual Result

- Errors like:

```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(100001) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib64/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib64/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib64/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib64/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/cloudigrade/util/management/commands/seed_review_data.py", line 49, in handle
    user1 = util_helper.generate_test_user(
  File "/opt/cloudigrade/util/tests/helper.py", line 467, in generate_test_user
    user = User.objects.create_user(
  File "/usr/local/lib64/python3.8/site-packages/django/contrib/auth/models.py", line 147, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib64/python3.8/site-packages/django/contrib/auth/models.py", line 141, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib64/python3.8/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib64/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib64/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib64/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib64/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(100001) already exists.
command terminated with exit code 1
```

## Additional context

We could sanity check that the user and other objects already exist instead of blindly trying to create them.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Sep 10, 2020, 11:57

We recently deleted the `seed_review_data` command. So, we don't need to do this now!
