### ISSUE TITLE
pid file left behind when listener crashes

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#761]
In GitLab by @infinitewarp on Nov 20, 2020, 15:27

## Summary

The `cloudigrade.pid` file is left behind sometimes when the listener crashes. This means when it tries t restart, it cannot.

## Steps to Reproduce

1. Kill the kafka socket in a way that looks like `OSError [Errno 22] Invalid argument` ([see also](https://sentry.io/organizations/cloudigrade/issues/2040104953/?project=2710933&referrer=slack))
1. ???
1. Restart the listener.

## Expected Result

- Exception is raised and stops the listener, and the pid file is removed before the process terminates. The next time the listener starts, is operates normally.

## Actual Result

- pid file remains after the process dies, and subsequent attempts to start fail.

## Additional context

- As discussed at standup, since the pid file _should_ contain the actual integer process ID, we could read its contents and check if the process actually exists. If no process, clear the pid file and continue.

Sample output from a stage deployment suffering this problem:

```
2020-11-20 19:55:18,197 | ERROR | 1 | listen_to_sources.py:handle:40 | requestid:None | Listener attempted to start with an existing pidfile. There should never be two instances of the listener running. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/lockfile/pidlockfile.py", line 77, in acquire
    write_pid_to_pidfile(self.path)
  File "/usr/local/lib/python3.8/site-packages/lockfile/pidlockfile.py", line 161, in write_pid_to_pidfile
    pidfile_fd = os.open(pidfile_path, open_flags, open_mode)
FileExistsError: [Errno 17] File exists: '/var/run/cloudigrade/cloudilistener.pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cloudigrade/util/management/commands/listen_to_sources.py", line 31, in handle
    with daemon.DaemonContext(
  File "/usr/local/lib/python3.8/site-packages/daemon/daemon.py", line 389, in __enter__
    self.open()
  File "/usr/local/lib/python3.8/site-packages/daemon/daemon.py", line 381, in open
    self.pidfile.__enter__()
  File "/usr/local/lib/python3.8/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.8/site-packages/lockfile/pidlockfile.py", line 87, in acquire
    raise AlreadyLocked("%s is already locked" %
lockfile.AlreadyLocked: /var/run/cloudigrade/cloudilistener.pid is already locked
```

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Nov 23, 2020, 13:26

unassigned @infinitewarp

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Nov 30, 2020, 10:50

Since we've seen our pods recover cleanly after this change, LGTM!
