### ISSUE TITLE
 Task "calculate_max_concurrent_usage_task" throwing error intermittently.

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#801]
## Summary

I observed Task "calculate_max_concurrent_usage_task" throwing error intermittently. There are few occurrences has recorded  by sentry and thill now those errors are from the production enverionment. Link as follow. 

[MaxRetriesExceededError ](https://sentry.io/organizations/cloudigrade/issues/2117798166/?project=1270362&referrer=slack)
[MaxRetriesExceededError ](https://sentry.io/organizations/cloudigrade/issues/2117798166/?referrer=slack)
 
[KIBANA LOGS](https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-15T08:59:58.570Z',to:'2021-02-15T09:07:06.413Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',key:'@timestamp',negate:!f,params:(query:'2021-02-15T09:05:33.837Z'),type:phrase),query:(match_phrase:('@timestamp':'2021-02-15T09:05:33.837Z')))),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:kuery,query:'@log_group:%22cloudigrade-prod%22'),sort:!()))

## Steps to Reproduce

There are no specific steps to reproduce this error . There error are thrown by the internal application task.

## Expected Result

- Application should not throw any error. 

## Actual Result

- Application is throwing error intermittently.

## Additional context

Error Links are added in summary sections.

**Comment by infinitewarp** [comment]
Since Kibana logs only persist for a relatively short period, here's a copy of the linked message:

```


@log_group:
    cloudigrade-prod-cw
@id:
    35979574812921132195659734892404544198073869079807262720
@timestamp:
    Feb 15, 2021 @ 04:05:33.837
@message:
    2021-02-15 09:05:33,837 | ERROR | 17 | trace.py:_log_error:255 | requestid:ee40fdc5-fd87-4b9a-b9f3-35fa09d8591c | Task api.tasks.calculate_max_concurrent_usage_task[calculate-concurrent-usage-e523f0a2-c058-419a-8a30-8325fc283fb7] raised unexpected: MaxRetriesExceededError("Can't retry api.tasks.calculate_max_concurrent_usage_task[calculate-concurrent-usage-e523f0a2-c058-419a-8a30-8325fc283fb7] args:() kwargs:{'date': '2021-01-26T00:00:00', 'user_id': 492291}") Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__ return self.run(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner reraise(*exc_info) File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise raise value File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner return f(*args, **kwargs) File "/opt/cloudigrade/api/tasks.py", line 566, in calculate_max_concurrent_usage_task self.retry() File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 707, in retry raise self.MaxRetriesExceededError( celery.exceptions.MaxRetriesExceededError: Can't retry api.tasks.calculate_max_concurrent_usage_task[calculate-concurrent-usage-e523f0a2-c058-419a-8a30-8325fc283fb7] args:() kwargs:{'date': '2021-01-26T00:00:00', 'user_id': 492291}
@owner:
    296389277756
@log_stream:
    cloudigrade-prod
_id:
    35979574812921132195659734892404544198073869079807262720
_type:
    _doc
_index:
    cwl-cloudigrade-prod-cw-2021.02.15
_score:
```

**Comment by infinitewarp** [comment]
We've recently made some changes to UserTaskLock and transaction handling that may affect or (hopefully) reduce the frequency of this issue. Let's hold this issue in the backlog until we've seen at least one more incident after releasing the recent changes.

**Comment by infinitewarp** [comment]
Curiously, it seems that something is preventing any concurrent usage objects from being saved _or_ something is deleting them shortly after they've been saved.

https://internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/concurrentusages/ returns an empty list which is *very* strange.

**Comment by infinitewarp** [comment]
Since Sentry has been quiet following recent deployments and nobody has raised any new relevant issues, I'm closing this issue as fixed!
